### ISSUE TITLE
🐛'dataVersion' is a required optionsIn parameter to WMLS_GetCap()

### ISSUE THREAD

**Issue by Pascal62223** [equinor/witsml-explorer#100]
**:bug: Describe the bug**
When WE authenticate the user against a WITSML server, it do send a WMLS_GetCap () request to the server with the parameter 'optionsIn' set to 'returnElements=header-only'

As per WITSML API specifications, 'dataVersion' is a required optionsIn parameter to be passed as part of the WMLS_GetCap() . Not doing so would result in the server returning a -424- error status code [Cf. Screenshot 1], which is then interpreted by WE as a 500 error [Cf. Screenshot 2]

In order to address the defect, and assuming that at this stage only WITSML 1.4.1.1 is being supported, the file backend OptionsIn.cs must be enhanced in scenario where the request is made to serve WMLS_GetCap()

After doing the change locally (in Fork) the authentication succeed. However as 'dataVersion' isn't a parameter required for all WMLS function it might be necessary to decide how handle the settings.

**To Reproduce**
1. After installing WITSMl Explorer and configuring it with Schlumberger WITSML developer test server 
2. Click on Server list
3. Authenticate 
    Verify first that the authentication is valid with another WITSML application \ toolbox 
4. See error screen shot below

**Expected behavior**
1. In scenario where input parameters to teh WMLS_** function being called is invalid, display proper error message as per WITSML specification error table. Only treat error to be (500) as ultimate fallback (InvokeAsync --> ExceptionMiddleware.cs default exception catch is to treat error as 500)
2. Fix VerifyCredentials and TestConnectionAsync to pass proper optionsIn parameter to the server

**Screenshots**

1. 424 Error code status returned when OptionsIn missing 'dataVersion' required parameter
![image](https://user-images.githubusercontent.com/77442348/104998797-c13b8700-5a66-11eb-9a3d-fac7b7fb88cb.png)

2. WE Error message after failure of authentication. 500 error code isn't matching teh server code being returned.
![image](https://user-images.githubusercontent.com/77442348/104999587-1035ec00-5a68-11eb-9d29-a232581f0ef5.png)

**Desktop (please complete the following information):**
  - Browser chrome
 - Version : Version 87.0.4280.141 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by Pascal62223** [comment]
My proposal would be to handle the 'optionsIn' of the WMLS_GetCap() separately from others WMLS_AddToStore or WMLS_GetFromStore.
Modifying the 'TestConnectionAsync()' to build a request with the 'optionsIn' fit to purpose for the WMLS_GetCap(). 

Would that be ok ? 
If yes I can do the change and get familiar with the submission process (Fork & PR) for that project.

**Comment by marmid74** [comment]
Yes, please go ahead and submit a pull request.

**Comment by Pascal62223** [comment]
OK. Thanks. Starting the change today.

**Comment by steinsiv** [comment]
Thanks for the PR, reviewing now.
I do not have access to SLB Dev server but that shouldn't be a problem
