### ISSUE TITLE
👉 ReturnElements setting in GetAllWells API

### ISSUE THREAD

**Issue by kongxy10** [equinor/witsml-explorer#1046]
**👉 Is your feature request related to a problem? Please describe.**
To fit for user story #687, the implementation of backend "GetAllWells"(/api/wells) API, was modified to use "returnElements=all" to query all wells from WITSML Server.

**Describe the solution you'd like**
I think it is worth to discuss this implementation again from both requirement and performance perspective.
For a WITMSL Server that contains a lot of wells, retrieving all properties of all wells might result in a very large response size, making the loading of well list page time consuming. As @Pascal62223 commented in the original user story, it might not be necessary to retrieve all properties in the initial well list request.
Maybe still retrieving well list by requesting a limited number of properties can improve the well list loading performance. Retrieving and displaying full properties of a specific well can be achieved through a subsequent request against single well with returnElements=all.

**Comment by janburak** [comment]
api/wells now uses returnElements=requested again. Eventual implementation of #687 would require implementing a separate route that fetches all the properties of a well.
