### ISSUE TITLE
Support for multiple logData in Logs [Question] 

### ISSUE THREAD

**Issue by carlospenedorocha** [equinor/witsml-explorer#1093]
Hello,

Given that the [standard 1.4 says that multiple logData](http://w3.energistics.org/schema/WITSML_v1.4.1.1_Data_Schema_with_Raster_v1.0/witsml_v1.4.1.1_data/doc/schema/grp_log.html) may occur in the log (for sparse updates):

`
<xsd:element name="logData" type="witsml:cs_logData minOccurs="0" maxOccurs="unbounded">
`

And here the support is for only one:
https://github.com/equinor/witsml-explorer/blob/a544aab125ead64ca25b8322bb4862b0b5c7e052/Src/Witsml/Data/WitsmlLog.cs#L75

Any plans to add it in the future?

Regards

**Comment by steinsiv** [comment]
Hi, there is no plan to add this that I am aware of unfortunately. Do you have an example request/response for this case?
Thanks!

**Comment by eliasbruvik** [comment]
Closing this as it's stale, and we do not have any use cases with multiple logData objects yet. Create a new issue with more details of how this should be handled if this still is required for some logs.
