### ISSUE TITLE
💡 Implement Message object - API

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#11]
**💡 Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Support for Message Object

Link to user Story: #140

**Comment by lindsve** [comment]
We are using Message objects in DtectLoss now, but are also keen on starting porting some of the code to C#. We'd like to have this project package and publish a nuget package of the Witsml project first though *wink wink*.

We'd be happy to provide contributions on other possible objects we need as well (like Risk)
