### ISSUE TITLE
Move code for reading witsml server credentials from config file to integration test project.

### ISSUE THREAD

**Issue by sudoole** [equinor/witsml-explorer#13]
**Describe the solution you'd like**
Old code used for reading server credentials from file is still present in codebase for Api. This functionality is currently only used for the integration test project. Therefore the code can be moved into that project instead.

Also consider:
* Renaming the configuration variables from e.g `Witsml:Host` to `WitsmlHost` or `WITSML_HOST`. 
* Support for reading config from environment and/or `dotnet secrets`

**Comment by janburak** [comment]
Completed in WitsmlExplorer.IntegrationTests.ConfigurationReader
