### ISSUE TITLE
User story:  RISK Object - API

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#142]
As a Developer, I want the WE API to support the RISK object so that I can use the WE API to perform operations on this object

### Acceptance criteria ###
- Ability to use the API to perform CRUD operations on the  RISK Object information

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by steinsiv** [comment]
All Operations (except Update?) have been added to the API through PRS: PR #387 PR #481 PR #483
