### ISSUE TITLE
 User story:  Tubular Object - API

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#148]
As a Developer, I want the WE API to support the tubular object so that I can use the WE API to perform operations on this object

### Acceptance criteria ###
- [ ] The WE API is extended to support the tubular object with create, read, update, delete

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by steinsiv** [comment]
Implemented through PR #1228 and PR #1211 
Closing...
