### ISSUE TITLE
User story:  Tubular Object - Frontend Edit/Delete

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#150]
As a Data Manager, I want to be able to edit and delete the tubular object in WE

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support edit and delete operations on  the Tubular object

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by steinsiv** [comment]
Implemented through PR #1228 
closing
