### ISSUE TITLE
User story:  RISK Object - Frontend Edit/Delete

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#152]
As a Data Manager, I want to be able to edit and delete the RISK object in WE

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support edit and delete operations on  the RISK object

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by janburak** [comment]
Implemented by #1328 and #1336
