### ISSUE TITLE
User story:  Formation Marker - Frontend View

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#153]
As a Data Manager, I want to be able to browse and view the Formation Marker object in WE

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support browsing the Formation Marker object

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by janburak** [comment]
Implemented by #1793
