### ISSUE TITLE
User story:  Formation Marker - Edit/Delete

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#154]
As a Data Manager, I want to be able to edit and delete the Formation Marker object in WE

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support edit and delete operations on  the Formation marker object

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by janburak** [comment]
Implemented by #1819 and  #1835
