### ISSUE TITLE
User story:  MUDLOG Object - Frontend View

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#155]
As a Data Manager, I want to be able to browse and view the MUDLOG object in WE

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support browsing the MUDLOG object

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by janburak** [comment]
Implemented by #1736
