### ISSUE TITLE
Create server initial screen with the advanced option

### ISSUE THREAD

**Issue by arunshellsquare** [equinor/witsml-explorer#1588]
- When user open Witsml Explorer first time user should view the Add server screen 
- User should be able to provide the following information 
   - Server URL 
   - Server Name 
    - Username 
   - Password 
- To connect the server with the proxy and advance link should be available 
- Option should be available to provide
   - Proxy Address 
   - Proxy port 
- It should be possible for the user to select the authentication for the proxy 
- User should be able to provide the Proxy username and password 
- User should be able to perform the test connection. A proper error message required to be display for failed connection 
- User should be able to save the connection and close the windows
- The server added should be visible in the Manage Connection Screen 

![WE-01a](https://user-images.githubusercontent.com/65786254/194276397-fe4325b5-f189-426c-9aa9-f5ad46633296.jpg)

**Comment by janburak** [comment]
> When user open Witsml Explorer first time user should view the Add server screen

Witsml Explorer will fetch the list of servers from the backend, so a regular user would not have to concern themselves with adding a server. Is there a reason for this to be the screen the user is welcomed with? Wouldn't it be better to show the "Manage server screen" from #1589 instead?
