### ISSUE TITLE
Create server popup screen

### ISSUE THREAD

**Issue by arunshellsquare** [equinor/witsml-explorer#1590]
**Old UI**
![s2](https://user-images.githubusercontent.com/65786254/194290453-abf66ebb-b7dc-4140-b834-f1206ada3dfe.JPG)
**New UI**
![WE-01d](https://user-images.githubusercontent.com/65786254/194290551-ced9a7d1-b057-4729-a0fb-6b890f2c8ba8.jpg)
- When user needs to add a new server, the user should view the Add Server screen.
- User should be able to provide the following information 
   - Server URL
   - Server Name 
   - Username 
   - Password 
- To connect the server with the proxy, an advance link should be available 
- Option should be available to provide
   - Proxy Address 
   - Proxy port 
- It should be possible for the user to select the authentication for the proxy 
- User should be able to provide the Proxy username and password 
- User should be able to perform the test connection. A proper error message required to be display for failed connection 
- User should be able to save the connection and close the windows
- The server added should be visible in the Manage Connection Screen.

**Comment by marmid74** [comment]
**Status meeting update 31.10.2022**
These are the required fields for Add Server pop up window. Any references to username/password, proxy/port are not relevant.
This is the current layout of Add server in WitsmlExplorer.
![image](https://user-images.githubusercontent.com/22211376/199004275-c86c9d52-a0c1-4d97-abea-8f2e6af3e869.png)


The field **version** could (optional) be displayed and disabled, as no other current version is available.
If added to Add server window, the version filed should be renamed to **Witsml version**, and the version number would be set to 1.4
