### ISSUE TITLE
Navigation bar at the top

### ISSUE THREAD

**Issue by arunshellsquare** [equinor/witsml-explorer#1594]
![image](https://user-images.githubusercontent.com/65786254/194302433-3bbc05ad-e728-4529-b490-300c47f1a624.png)
- The navigation required to be displayed based on the selection of the tree node.
- User can navigate to the pages on clicking the navigation bar at the top of the page. 

![image](https://user-images.githubusercontent.com/65786254/194302521-63d477d1-83cf-4ae3-8706-63e07768da6f.png)

**Comment by marmid74** [comment]
Status 21st Dec. 2022 : 
Agreed to update this issue with new design, GUI design proposal to be added by Shellsquare.
Create separate PR on this issue, including the new GUI design, (not including read/write icon)
