### ISSUE TITLE
Use `MapPatch` in Routes.cs

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#1647]
**Is your feature request related to a problem? Please describe.**

As of aspnetcore7, there is now a `MapPatch` method on endpointroutebuilder extension
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutebuilderextensions.mappatch?view=aspnetcore-7.0

**Describe the solution you'd like**
Replace the generic `MapMethods` in `Routes,cs` with the new `MapPatch` method
```
app.MapMethods("/witsml-servers/{witsmlServerId}", new[] { HttpMethods.Patch },WitsmlServerHandler.UpdateWitsmlServer, useOAuth2, AuthorizationPolicyRoles.ADMIN);
```

**Additional context**

`WitsmlExplorer.Api/Extensions/WebApplicationExtensions.cs` needs to be updated accordingly to count for the new PATCH method

**Comment by janburak** [comment]
@KindCoder-no
