### ISSUE TITLE
User story:  TRAJECTORY - Frontend - Rename Trajectory

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#166]
As a Data Manager, I want to be able to rename a trajectory (similar functionalty as for renaming well, wellbore, log, etc...)

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support rename  operation on  the trajectory object

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by HoldampfIldiko** [comment]
INT - TDE @aszalos-roland

**Comment by janburak** [comment]
duplicated by #183
