### ISSUE TITLE
💡 Word-wrap in ContentTable

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1667]
**💡 The problem**
Content tables do not word-wrap on long inputs.
![image](https://user-images.githubusercontent.com/66632214/202127120-79a024cf-fc91-43f8-b9ad-46054cc82dbc.png)

**The solution I'd like**
It should be possible to specify, for example, an optional maxLength property in ContentTableColumn that would make the cells in a specific column word-wrap.

**Alternatives I've considered**
An alternative I have considered was to insert "\n" into the table data string. It did not work with the current table cell element.

**Comment by KindCoder-no** [comment]
I don't think MUI supports word-wrap in their Table Cell, because the cell resizes itself based on the content. 

Also, it does not support any html/text encoding to make a new line. For example, `<br>`

**Comment by KindCoder-no** [comment]
Also tried using css, Still no effect

**Comment by janburak** [comment]
Closing due to a workaround from #1678
