### ISSUE TITLE
User story:  TRAJECTORY - Frontend - Delete trajectory stations

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#167]
As a Data Manager, I want to be able to delete individual trajectory stations in a Trajectory

### Acceptance criteria ###
- [ ] The WE  frontend is extended to support deleting operations on  individual surveys.
- [ ] It is possible to select one/several trajectory stations and you can delete them

Also, here are a few points that need to be addressed:
- [x] Dependency to user story #165 
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by HakonHesselberg** [comment]
Hi,

I would like to attempt solving this issue. Is there any way to assign this to me?

**Comment by marmid74** [comment]
@HakonHesselberg - Thanks for your request.
Please submit an [issue feature request](https://github.com/equinor/witsml-explorer/issues/new/choose) describing shortly your proposal to solve this user story. 
Notice that there is a dependency to #165

cc: @sasiv, @thomash1972
