### ISSUE TITLE
User story:  General - Improved Logging

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#171]
As a **Data Manager**
I want **to be able to browse a log showing information about edit operations initiated by a WE user**
so that **I can take actions if I see that a user has made a mistake editing the datasets**

### Acceptance criteria ###
- [ ] Ability to see who has initiated operations, what has been edited and when.
- [ ] 

Also, here are a few points that need to be addressed:
- [ ] Only summary information about the operation is needed
- [ ] I do not need an undo function
- [ ] Data deleted or changed does not need to be stored

### Resources ###
-  Resource A
-  Resource B

**Comment by janburak** [comment]
Implemented by #1445 and #1707
