### ISSUE TITLE
User story:  General - Progress View

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#172]
As a  **Data Manager**
I want **to see a full overview of all running and completed jobs including progress and status**
so that **I will know if/when a job is completed, and evaluate the load on servers**

### Acceptance criteria ###
- [ ] Always match between running jobs and list
- [ ] Finished jobs must be OK'ed out

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Resource A
-  Resource B

**Comment by janburak** [comment]
Impemented by #1445
