### ISSUE TITLE
User story:  Export log to .csv

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#173]
As a Data Manager
I want to select one log from a Well, and export the log data to a .csv file (Excel friendly)

### Acceptance criteria ###
-  In the selected  log you want to export, select "Download to  .csv" and one file in .csv format is downloaded to the users laptop/pc.

### GUI Workflow ###
1.	From Sidebar menu expand to Logs /Time/"Specific log"
a.	The content view will show the list of Mnemonics (curves) for that particular log
2.	From Content view
a.	select (toggle checkbox) which mnemonics to export
b.	mouse right click, in LogCurveInfoContextMenu, select “Open”
3.	Adjust start/end index and click button “View curve values”
4.	Select button “Download all as .csv” . 
a.    The filename should be in following format "Wellbore name"-"Log name"-YYYY-MM-DD T HH:MM:SS.csv
b.    Remove special characters in the wellbore name and log name and replace  "/" with underscore "_"
c.    Column header is put in row 1 of the .csv file. Each curve is represented as:   **Mnemonic[unit],**      
5.	(NOT SPECIFIED YET) Warning Dialog window:  
If selected set of curves are too many and/or the index range is too large (months), the user shall get a warning to reduce the selected ranges so that the export process not times out/ allocates all resources of the witsmlExplorer server. Not sure where the threshold should be set. Experiences during implementation of this user story will most likely give an idea what the acceptable threshold/limit should be. This will be based on experience on performance (how long time the export the will take).

**STEP 1 and 2**
![image](https://user-images.githubusercontent.com/22211376/116564535-5c18ec80-a905-11eb-93ed-34c1ec334178.png)
**STEP 3**
![image](https://user-images.githubusercontent.com/22211376/116563585-730b0f00-a904-11eb-8abb-f027c80e23b7.png)
**STEP 4**
![image](https://user-images.githubusercontent.com/22211376/116564412-3ee41e00-a905-11eb-8b5c-05a3a9845ea5.png)

### REQUIREMENTS - CONSTRAINTS ### 
1.	The use-case limits the export to one selected log at a time, with a selected set of mnemonics(curves) for a specified index range. (See GUI workflow)
2.	 First version of US need only to support export to .csv format 

### CONSIDERATIONS ###

- Time based logs contains a huge amount of data. One log may potentially contain millions of rows, and the size of the file would be hard to read for “ordinary” tools. 10 000 rows (approximate 4 hours of time-based data) would result in a 2MB file in CSV format
- Large CSV file without header/meta information (ex. date-time for export) will be difficult to handle/use.
- Export of large (in particular time based) multiple logs at the same time will create a considerable load on both the WitsmlExplorer server and witsml server. Hence the constraint to limit export of only one log at a time, and not allow for batch exports of logs. 
- Result may need to be cashed/temporary stored on disk and compressed before sent to user. The response time will long 
- Data from a Log are fetched from witsml-servers 10 000 rows/request and made available for frontend. ( 10 000 rows/request is a witsml server constraint) The use-case must solve the technicalities for temporarily store on server-disk/cache the data and enable a file download of the complete logdata result as a csv file. Avoid to fetch the same dataset twice (once as the user completes steps 1-3, and once as the user click “Download as .csv” in step 4).

### Resources ###
-  TDE
-

**Comment by HoldampfIldiko** [comment]
DEV - TDE @aszalos-roland
