### ISSUE TITLE
User story:  Import  log from .csv

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#174]
As a Data Manager
I want to be able to Import log data from a defined .csv file format to a WITSML server in the context of a selected wellbore.

### Acceptance criteria ###
- on an existing log object , import additional log data from a pre-defined .csv format (same format as Export log user story.)
- If the import .csv format is not in the correct format, WE will inform me about this without trying to import the data

Also, here are a few points that need to be addressed:
- [X] The target Log need to exist before importing the data from right clicking on the Log Object
- [ ]  alternatively the import function will create the Log if needed (Log name then need to be specified in the .csv file ? 
- [ ] Alternatively you could allow the import to be initiated from a generic menu item, but require that the well, wellbore as specified in the .csv must exist, and prompt the user for which existing Log the data should be imported to
- [X] If a curve does not exists in log, the solution must resolve the datatype upfront. This can be done based on unit. If unitless, the solution must resolve if the datatype is string, numeric or date
- [X] If a curve does not exists, solution must add values on mandatory properties on curve (datatype, unit, uid?, description?).
- [X] Witsml servers Datapoint limitation - maximum 10 000 rows for each updateInStore, so .csv with more rows, need to be divided into multiple updateInStore operations.

### Resources ###
-  Development: TDE
-  Lead: Equinor

**Comment by HoldampfIldiko** [comment]
DEV- TDE @aszalos-roland

**Comment by marmid74** [comment]
This user story is named VERSION 1, of Import log from .csv. Implemented by TDE Group.
Extended features, named VERSION 2, of Import log from .csv is specified in user story #554
