### ISSUE TITLE
User story:  LOG - Simple squiggly line log curve viewer

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#180]
As a data manager
I want to View the selected log curves in a simple Log Curve Viewer
so that I can get a visual representation of the numerical data

**Comment by janburak** [comment]
Would require:
- downsampling (probably)
- picking range
- plotting while fetching

Might want to wait for ETP

**Comment by janburak** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/66632214/da2edbb3-8399-41fa-b57e-0067c1044de0)

**Comment by asbhe** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/90765040/2d319c9e-3fe0-41ae-ac3d-26e098b247f1)

**Comment by janburak** [comment]
From WE-400 Simple Visualization for selected Logs:
Select 1 or more curves.

Display the values in tracks as “squiggly lines” noe numerical values.

When opening, one should have the option to select a spesific interval (top to bottom is the default).





OPTIONAL:

Use a config file where the scaling and color for each mnemonic is specified:

MNEMONIC NAME, LOW, HIGH, COLOR, EXP UNIT

GS_ROP, 0, 1, red, m

GRAX, 20, 50, blue, ohm

….
