### ISSUE TITLE
User story:  WELLBORE Frontend - Update attributes in property window

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#181]
As a Data Manager, I want to be able to right click on a WELLBORE, and update the attributes in the property window.

NB: This backlog Item only covers single instance update, not batch update of multiple object instances): 

EDIT, NO BATCH, NO ENUM: 
nameWellbore, nameWell, number, suffixAPI, numGovt, dTimKickoff, md, tvd, mdKickoff,tvdKickoff, mdPlanned, tvdPlanned, mdDubSeaPlanned, tvdSubseaPlanned, dayTarget

EDIT, BATCH, OPEN ENUM:
statusWellbore, purposeWellbore, typeWellbore, shape

Tasks
- [ ] Extend property pane for Wellbore with new properties and make them editable
- [ ] Connect the edited wellbore with a job in backend, through backend API, to persist the changed properties

### Acceptance criteria ###
- [ ] Ability to right click on a WELLBORE Object instance, and update the WELLBORE attributes listed above.

**Comment by steinsiv** [comment]
These properties are now made editable in PR #639 and covers GUI updates through `wellbore` property pane

The `shape?: string;` has also been added, not editable but not in the user story list.

Note: the changes are not persisted to backend, and `nameWell` is to be be changed in `Well` properties pane. A new task has been added to encompass this.
