### ISSUE TITLE
🐛Environmental variable references no longer working 

### ISSUE THREAD

**Issue by kongxy10** [equinor/witsml-explorer#1816]
**:bug: Describe the bug**
A previous change : https://github.com/equinor/witsml-explorer/pull/1735
Added "NODE_ENV" prefix to the variable name when pushing environmental variables to the build output.
e.g. WITSMLEXPLORER_API_URL->NODE_ENVWITSMLEXPLORER_API_URL
This resulted in the current references through process.env, e.g.  process.env.WITSMLEXPLORER_API_URL became ineffective.
(Because it has changed to process.env.NODE_ENVWITSMLEXPLORER_API_URL)
**To Reproduce**
Add WITSMLEXPLORER_FRONTEND_URL value and WITSMLEXPLORER_API_URL in .env file

**Expected behavior**
The returned base path of AssetLoader and the backend url should be modified

**Screenshots**
The base path of AssetLoader and the backend url are remain unchanged

**Comment by kongxy10** [comment]
further thoughts:
It seems that the webpack config part in next.config.js now becomes useless, since now all of environment variables starts with NEXT_PUBLIC_ prefix, which means they will directly be exposed to runtime (browser), we no longer need to push them into runtime by code manually. Maybe we can remove it. @janburak 

relevant documentation:
https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

**Comment by janburak** [comment]
I have not worked with webpack config before so I am unsure, but what you are proposing does make sense. Feel free to make the appropiate adjustments.

**Comment by kongxy10** [comment]
@janburak  Thanks! PR raised #1818
