### ISSUE TITLE
User story:  Frontend - Update LOG attributes in property window

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#182]
As a Data Manager, I want to be able to right click on a LOG, and update the attributes in the property window.

serviceCompany
runNumber

### Acceptance criteria ###
- [ ] Ability to right click on a  LOG Object instance, and update the LOG attributes listed above.

**Comment by ssf93** [comment]
Checking through the PDS-client we would like;
serviceCompany 
runNumber 

to be viewable and also edit-able
