### ISSUE TITLE
User story:  Frontend - Update TRAJECTORY attributes in property window

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#183]
As a Data Manager, I want to be able to right click on a TRAJECTORY, and update the attributes in the property window.

NB: This backlog Item only covers single instance update, not batch update of multiple object instances): 

EDIT: 
AziRef, serviceCompany, commonData.sourceName, name

### Acceptance criteria ###
- [ ] Ability to right click on a  TRAJECTORY Object instance, and update the TRAJECTORY attributes listed above.

**Comment by ssf93** [comment]
List of what we want VIEWABLE in addition to what is there today, under the Trajectory object:
No.
mtf
gtf
dispNs
dispEw
vertSect
dls
rateTurn
rateBuild
gravTotalUncert
dipAngleUncert
magTotalUncert
sagCorUsed
magDrlstrCorUsed
gravTotalFieldReference
magTotalFieldReference
magDipAngleReference
statusTrajStation
gravAxialRaw
gravTran1Raw
gravTran2Raw
magAxialRaw
magTran1Raw
magTran2Raw
gravAxialAccelCor
gravTran1AccelCor
gravTran2AccelCor
magAxialDrlstrCor
magTran1DrlstrCor
magTran2DrlstrCor
sagIncCor
stnMagDecIUsed
stnGridCorUsed
dirSensorOffset
magTotalFieldCalc
magDipAngleCalc
gravTotalFieldCalc

**Comment by ssf93** [comment]
The first few we would like this order as default in the horizontal view:
No.
uid
dTimStn
typeTrajStation
md
tvd
incl
azi
dls
mtf
gtf
dispNs
dispEw
vertSect
The others can be added after.
