### ISSUE TITLE
User story:  Update MNEMONIC attributes in property window

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#184]
As a Data Manager, I want to be able to right click on a MNEMONIC, and update the attributes in the property window.

NB: This backlog Item only covers single instance update, not batch update of multiple object instances): 

EDIT, BATCH, ENUM
typeLogData, traceState

EDIT, NO BATCH, OPEN ENUM
mnemonic, unit, mnemAlias, 

EDIT, BATCH, NO ENUM
nullValue, sensorOffset

### Acceptance criteria ###
- [ ] Ability to right click on a  MNEMONIC Object instance, and update the MNEMONIC attributes listed above.

**Comment by Pascal62223** [comment]
By MNEMONIC you mean a LogCurveInfo element. Correct ?  (What is referred in WITSML as cs_logCurveInfo)

To make sure I understand properly "not batch update of multiple object instances". The user story indicates that for example 'nullValue' and 'sensorOffset' can be updated in Batch for more than one  entry within the same logCurveInfo.  Correct ?
