### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#1840]
**Is your feature request related to a problem? Please describe.**
See user story #1809 

**Describe the solution you'd like**
Extending the User settings menu with dark mode
![image](https://user-images.githubusercontent.com/22211376/233976536-e283308c-375d-4290-b3b9-db9d39e04323.png)

![image](https://user-images.githubusercontent.com/22211376/233976026-d2b9a143-b8af-44ce-ace9-f8f4ac0b2ccc.png)

![image](https://user-images.githubusercontent.com/22211376/233971136-2e50787a-9014-4722-a95d-26760fae4ab4.png)

![image](https://user-images.githubusercontent.com/22211376/233971486-fa7efc0c-0514-4ee4-882c-6de40269b218.png)

**Comments**
GUI presented by ShellSquare to Equinor 20.th April
Proposed enhancements for dark mode are accepted/approved by Equinor team

**Comment by marmid74** [comment]
This issue implements user story #1809

**Comment by ThomasHalland** [comment]
screenshots looks amazing
