### ISSUE TITLE
User story:  Update RIG attributes in property window

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#185]
As a Data Manager, I want to be able to right click on a RIG, and update the attributes in the property window.

EDIT, BATCH, OPEN ENUM
Owner, typeRig, manufacturer, classRig, approvals, registration,

### Acceptance criteria ###
- [ ] Ability to right click on a  RIG Object instance, and update the RIG attributes listed above.

**Comment by Pascal62223** [comment]
Considering below properties are optional (and not always set by producer) being able to edit/update them might be considered : 
* isOffshore

Where are the "nullvalue", "sensorOffset", "traceState" properties for the rig object ? Can't find them. Aren't they part of the LogInfo.

**Comment by janburak** [comment]
Issue updated with regards to already implemented functionality

**Comment by janburak** [comment]
Should batch editing involve rigs on a single wellbore, or rigs from across multiple wellbores/wells? In the latter case, the issue should be groomed to describe how to mark multiple rigs for batch edit.
From WE-26: Use filter to find all Rigs, and batch set properties on key rig object attributes for all
