### ISSUE TITLE
Preferences for formatting datetimes

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#1863]
As a user of WITSML Explorer I want to be able to set my preferred display settings for the datetime format so that I can display the data according to my task at the moment.

Switch between a minimum of two formats for displaying datetime (for instance raw, and "natural") in the SettingsModal.

Natural: 24.03.2023 17:49:24.000 or 24.03.2023 17:49:24
Raw: 2023-03-09T17:49:24.000+01:00  (as is used today)

This would require dateTimeFormat in DateFormatter.ts to be dependent on the chosen format.

The chosen format should be stored in local storage, same as for other settings.

**Comment by janburak** [comment]
From Jira WE-786

**Comment by asbhe** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/90765040/145a4fb8-148a-4ae2-aa47-4d3532c1e367)
@harigopalmg
