### ISSUE TITLE
Api.Workers tests

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1907]
Implement unit tests for the following classes in the Api.Workers namespace

DeleteWellboreWorker
DeleteWellWorker

ModifyBhaRunWorker
ModifyMudlogWorker
ModifyRigWorker
ModifyRiskWorker
ModifyTrajectorystationWorker
ModifyWbGeometryWorker

WorkerTools
ReplaceComponentsWorker
ReplaceObjectsWorker

**Comment by robertbasti** [comment]
Only those classes exist:

DeleteWellboreWorker
DeleteWellWorker

ModifyTrajectorystationWorker
ReplaceComponentsWorker
ReplaceObjectsWorker

WorkerTools
