### ISSUE TITLE
Search by Rig

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#1910]
### User story: [User can select to search by rigs instead of by Wells]  ###

As a USer
I want to find all the wellbores drilled by a Rig
so that I can work on the dataset in Rig Context

### Acceptance criteria ###
- User shall be able to change search criteria from Wells (today) to by Rigs.
- List all well/wellbores when entering parts of rig name in search bar
- The results shall still be a listing of the wells (so same hierarchy as "usual")

Also, here are a few points that need to be addressed:

- UX:  Can the generic search bar be used, only that you select that you want to search for RIG instead of the default WELL, or do we need an additional attribute where the user defines what he wants to search by. 
- UX Should should implemented so that it can be further extended in the furture. if you want to  search using other contexts (e.g Field, Service Company, etc...)
- Wildcard support.

### Resources ###

-  Lead resource: [name/company]
-  Contributors: [list names/company]

![image](https://github.com/equinor/witsml-explorer/assets/123538108/b91a3ece-bbb7-43d9-8ddd-f50b23cfa185)

**Comment by janburak** [comment]
Name filtering should reuse wildcard functionality from #1917 
~~One would most likely have to fetch all rigs in api and the filter on name there (double check with WITSML api spec).~~

One way to solve the issue, without increasing the load when connecting to a WITSML server in frontend, would be to fetch all rig names only when the user picks the "Rigs" option from the dropdown. Some feedback should be given to the user to indicate that rigs are being fetches, such as for example reusing WellProgress in both the sidebar and the content view. The fetched rigs-well-wellbore mapping should likely be saved separately in the NavigationState.
