### ISSUE TITLE
Show progress on ongoing jobs

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1911]
Add a `Progress` field to `JobInfo` (likely `int`).
Update `Progress` in `CopyLogDataWorker` after every executed update query with the estimated progress percentage:  `(currentIndex-startIndex)/(endIndex-startIndex)*100`.
In JobsView, use `Progress` to augument the `Status` column if the status is running and progress has a non default value as such: "Running (progress%)".

Future work: 
* auto refresh progress percentage in JobsView
* show start, current and end indexes for CopyLogData jobs

Moved from WE-306

**Comment by vaclavbasniar** [comment]
It seems to need some rework on job execution tree side to work properly
