### ISSUE TITLE
Missing Data Agent

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#1931]
As a Data Manager 
I want to select a number of well/wellbores, where I can select 1 or more attribute to look for and the agent will run through the wellbores and check if there are data in the selected attributes or not (it may also give a report on number of objects etc...
so that  I can get a quick overview of where there may be missing data etc....

### Acceptance criteria ###
-  right click after you have made a selection and run the agent
-  ability to select what attributes, objects, or other spesific things to look for.
- MVP:  check if following objects / attributes are present: numLicense (well), serviceCompany (log, trajectory), FormationMarkers, MudLogs, Rigs, Risks.
- Each check can be turned on/off before running the agent

Also, here are a few points that need to be addressed:
- the results shall be presented in a report which can easily be exported or copied
- results shall have a nice fomatting so that it is easy to see what is missing pr. well/wellbore

### Resources ###

-  Lead resource: [name/company]
-  Contributors: [list names/company]

![image](https://github.com/equinor/witsml-explorer/assets/123538108/f0ae889b-4cc7-4bcc-9b99-1564e0cec6c6)

**Comment by janburak** [comment]
EDIT: the following has been implemented as part of #1953 and can be reused in this issue.

After starting the job, a modal with a spinner should be shown. The modal should have an option to "run in background" (just closes the modal), and optionally a cancel button (would need to figure out how to cancel a job).

The result should be available in the JobsView. Would need to figure out how to add an attachment to a job. Opening the result through the JobsView should result in the same view one would get when waiting in the modal to complete.

Ability to download the result as CSV. The user should be able to pick which format they want:
* csv where each of the toggleable items is its own column, and the cells contain the names of the wellbores that are missing the items
* csv where each wellbore has its own column, and the cells contain the items that are missing
