### ISSUE TITLE
Expand Rigs group in sidebar

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1939]
Show individual rigs in the sidebar under the Rigs group the same way as Trajectories or Tubulars. One difference is that we do not show any components under rigs, so clicking a rig in the sidebar should navigate to the rigs group view.

Split from WE-336

**Comment by asbhe** [comment]
**Illustration of this case**
Today rigs are only available in content window:
![image](https://github.com/equinor/witsml-explorer/assets/90765040/2b1563c3-c7d1-4ab6-ac7e-d3e9a88c69ab)

We want them available in sidebar window as illustrated here:
![image](https://github.com/equinor/witsml-explorer/assets/90765040/12dbd213-9f58-4c76-b550-7d8a98524df4)
