### ISSUE TITLE
Change Well/Wellbore UID (Copy all data to new well/wellbore)

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1942]
Blocked by #1901 

Moved from WE-12, WE-13

**Comment by robertbasti** [comment]
can be done after copy wellbore functionality, change only Wellbore UID

**Comment by robertbasti** [comment]
maybe not useful (can be done

**Comment by robertbasti** [comment]
Usecase solved by copying wellbore with a different UID
