### ISSUE TITLE
Offset log curve data within range

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1949]
Expand #1948 with functionality to specify a range within which data points will be offset. Take input from the user by showing a modal when attempting to perform the operation, with the whole range as default (the whole range is the functionality of #1948).
The operation should only move data points into a "gap" within which there are no preexisting data points (except for the ones to be moved), look at point 1 in the picture. Take care to clean up the data points that were moved (point 2 in the picture).
![image](https://github.com/equinor/witsml-explorer/assets/66632214/ab1af0ca-bead-42dd-999f-882e6c1e441d)

Split from WE-175

**Comment by eliasbruvik** [comment]
Completed by #2459
