### ISSUE TITLE
New field view with a text field where you can input a query and see the XML result

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1951]
Replicate PDS WITSMLstudio functionality where the user can enter an arbitrary query and the API will forward it to the target WITSML server as is, and then show the result as is.
Include:
* ReturnElements options
* Template for every object type / ReturnElements combination
* Get/Add/Update/Delete function options

Optionally / future work:
* XML formatting
* Syntax highlighting
* XML validation

Moved from WE-343

Split into: #2013 #2014 #2016

**Comment by asbhe** [comment]
Can probably borrow code from PDS client here (also open source).
