### ISSUE TITLE
Log Header Consistency Check

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1953]
Add functionality when right-clicking a log to perform a header consistency check.
The check will compare the start and end index of each LogCurveInfo with the actual index of the first and last data point of each curve.
The last data point for each curve can possibly be found using the requestLatestValues OptionsIn keyword.
The result should look like:
| Mnemonic  | Header Start | Data Start | Header End  | Data End |
| ------------ | -------------- | ----------- | -------------- | ---------- |
| GRAX  | **_450_** | **_480_** | 560 | 560 |

The result should be available asap or later in jobs view like in https://github.com/equinor/witsml-explorer/issues/1931#issuecomment-1582730841.

Moved from WE-408

**Comment by ThomasHalland** [comment]
Need to check if requestLatestValues uses the potentially corrupt end index or not

**Comment by asbhe** [comment]
@eliasbruvik Burde nokk hatt denne informasjonen tilgjengelig i applikasjonen:
"The check will compare the start and end index of each LogCurveInfo with the actual index of the first and last data point of each curve."
I dag når man klikker på "check log header" får man bare til svar at det er ok, men man vet ikke nødvendigvis hva som er ok.
![image](https://github.com/equinor/witsml-explorer/assets/90765040/fd0061b2-5b1a-45e6-88d8-d0370f2d49e5)
