### ISSUE TITLE
Consistent copy mnemonic behavior

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1955]
Currently, the "copy to server" functionality deletes the existing mnemonics, and only then starts the copy operation. Meanwhile when performing the "paste" operation, the mnemonics are spliced by removing the target interval from the target, and then filling it with the source data. Splicing happens on the WITSML server side, the only difference in our API is that we call delete on the mnemonics with "copy to server" but not "paste". To ensure consistent behavior, both "copy to server" and "paste" should show the same modal when attempting to copy mnemonics. The modal should show an option to either replace (current "copy to server" functionality) or splice (current "paste" functionality) the data. Both operations should be sufficiently explained in the modal.

Moved from WE-410

**Comment by eliasbruvik** [comment]
It seems like other properties of the LogCurveInfo object are only copied when the corresponding LogCurveInfo object does not already exist in the target log. When the object exists, and it therefore splices the logs, the properties are not copied. I don't know if this is intended or a bug, but it's worth to keep in mind when making the behavior consistent.

Edit: Created an issue for it: #2205

**Comment by robertbasti** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/44800029/dfbdc229-34f7-4f71-ac6f-2d816ef7e6b1)
