### ISSUE TITLE
Handle maxDataNodes and maxDataPoints 

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1957]
When attempting to copy log data from a server with larger values of maxDataNodes or maxDataPoints, the copy operation will fail due to attempting to send more data than the target server allows. Handle this by reworking all workers that handle log data to take maxDataNodes or maxDataPoints into consideration by splitting Add/Update queries into smaller chunks if they are larger than what the target server allows.

**Comment by ThomasHalland** [comment]
Highpriority if it creates problems for our current set of servers/datasets.

**Comment by vaclavbasniar** [comment]
What exactly maxDataNodes and maxDataPoints represent in the context of WitsmlLog objects? E.g. are the data nodes equal to WitsmlLog and the data points equal to WitsmlLogCurveInfo?

**Comment by asbhe** [comment]
Nodes is numbers of rows, points is number of cells. If that answers your questions.

**Comment by asbhe** [comment]
> What exactly maxDataNodes and maxDataPoints represent in the context of WitsmlLog objects? E.g. are the data nodes equal to WitsmlLog and the data points equal to WitsmlLogCurveInfo?

Ok, so maxDataPoints are number of curves/mnemonics in a log. In the case we looked at, where the number was 7000000, that means 700 curves. (Multiply nodes with number of curves, and you'll receive maxDataPoints.)

**Comment by vaclavbasniar** [comment]
test environment needed
