### ISSUE TITLE
Rework EditInterval datetime input

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1991]
Rework EditInterval input datetime input as mentioned in #1804.
![image](https://github.com/equinor/witsml-explorer/assets/66632214/2de10535-6aff-475a-844e-c0300428b13c)
Clicking on, for example, days, should mark only days. After entering a day, the input should not hop to months, and so on. Pressing tab should also hop between day-month-year hours-minutes-seconds. After entering seconds and pressing tab in start index, the input should hop to the start of end index.

The same input component should be also used in the AdjustDateTimeModal

Dots and colons should not be editable.

Keyboard arrow up-down should adjust the marked box by one.

**Comment by robertbasti** [comment]
The same input component should be also used in the AdjustDateTimeModal - will be done by a new task

**Comment by eliasbruvik** [comment]
Implemented in #2061
