### ISSUE TITLE
Make CopyLogDataWorker conform to WITSML specification

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1997]
When attempting to copy log data to a log on the Petrolink server, and the mnemonics do not exist on the target, the query that attempts to create the mnemonics in `VerifyTargetHasRequiredLogCurveInfos` fails with error `-436` "When an update adds a new column-identifier to a systematically growing data-object, a structural-range must not also be specified. ".

The query should most likely be adjusted, so that the `LogCurveInfo`s have their `minIndex`, `maxIndex`, `minDateTimeIndex`, and `maxDateTimeIndex` set to `null`.

Given that the `LogCurveInfo`s come from the `targetLog` parameter, the `LogCurveInfo` changes should be performed on a clone of the object, so that we do not mutate `targetLog`. Possibly a clone operation should be implented for `LogCurveInfo` (or eventually for all WITSML objects).

Also, when the `-436` error occurs in `VerifyTargetHasRequiredLogCurveInfos`, the job continues, disregarding the error (eventually leading to `-452` because the `LogCurveInfo`s are missing on the target). `VerifyTargetHasRequiredLogCurveInfos` should cause the whole job to fail on unsuccesful result.

**Comment by eliasbruvik** [comment]
I'm not able to reproduce this bug. It is either already fixed, or it was fixed when Petrolink updated a schema on their server.
