### ISSUE TITLE
Import LAS files

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1999]
Expand .csv import functionality with support for LAS files. Would require example LAS files for testing.

One way to do it would be to reuse ImportLogDataJob and in frontend parse the LAS file to fill out the job the same way as for .csv.

**Comment by ssf93** [comment]
Export and import function. Pop-up windows for importing/exporting where a simple view of the 50 lines is visible, and then be able to exclude the header based on the amount of lines vertically

Las formats, with and without header? I will have to investigate difference between LAS1 LAS2 LAS3 formats and how different the headers are in the different formats

Suggestion for simple pop-up:
![image](https://github.com/equinor/witsml-explorer/assets/133205654/6727c230-6538-4b35-bb77-165d1f40a2d3)

**Comment by ssf93** [comment]
[LAS file for Jan.txt](https://github.com/equinor/witsml-explorer/files/12395140/LAS.file.for.Jan.txt)
Example LAS file
