### ISSUE TITLE
User story: Frontend - Update logCurveInfo attributes in property window

### ISSUE THREAD

**Issue by ssf93** [equinor/witsml-explorer#2009]
As a Data Manager, I want to be able to right click on a curve/mnemonic, and update the attributes in the property window.

NB: This backlog Item only covers single instance update, not batch update of multiple object instances):

Acceptance criteria
 Ability to right click on a curve/mnemonic Object instance, and update the curve/mnemonic attributes listed below:

![image](https://github.com/equinor/witsml-explorer/assets/133205654/5fa224e7-7928-4620-9f57-e2ad01760277)
Example above how it looks today, we also would like:

**unit - editable
curveDescription - editable
typeLogData - uneditable
mnemAlias - uneditable**

**Comment by janburak** [comment]
A query updating LogCurveInfo requires the mnemonic element to be present
