### ISSUE TITLE
Query View - further enhancements

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#2016]
Based on #1951. Stub for further improvements of Query View

- [x] Create object with query functionality. A menu item to create a new object that brings the user to the QueryView with the query prefilled with the correct object type, well uid, wellbore uid, and a newly generated object uid.
- [x] Free-text OptionsIn field (like in PDS).

Potential QoL features

- [x] Multiple "tabs" of input-output pairs
- [x] XML formatting
- [x] Syntax highlighting
- [x] WITSML-suggestions for autocomplete
- [x] XML validation
- [x] Easier editing? For example a pen icon appearing next to a `<name/>` that expands the tag to `<name><name/>`.

**Comment by eliasbruvik** [comment]
All suggestions have been implemented as a part of their own sub-issues.
