### ISSUE TITLE
Download all log data as a parquet file

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#2023]
Select a number of mnemonics -> right click -> download as

Read log data and continually save it to a file. Upload the file to, for example, Azure blob storage, and make it available for download through for example Jobs View. Would require handling large files.

Requested by @stili

**Comment by eliasbruvik** [comment]
Downloading all log data is implemented for csv and soon for las files, so seems like this might not be needed anymore. Create a new issue if anyone still needs this.
