### ISSUE TITLE
🐛Huge performance issue in Tasks/Workers, LINQ issue

### ISSUE THREAD

**Issue by petrlicman** [equinor/witsml-explorer#2039]
**:bug: Describe the bug**
In a lot of workers there is Task used incorrectly in IEnumerable which is not materialized once, but reenumerated by each call to this list of tasks. This leads to re-executing this list of tasks, so many of tasks is called 2x, 3x or even more. 

**To Reproduce**
Check code of all workers and another classes where Tasks are used in IEnumerable
Screenshot of one place where this issue is

![image](https://github.com/equinor/witsml-explorer/assets/133652090/263d93b5-c7e0-4f5a-ba99-f0da06a7b1f8)

GetWitsmlObjectById is called twice for _expandableObjects.
Same issue in another workers like CopyLogWorker.... etc..

**Comment by eliasbruvik** [comment]
Nice catch! Stumbled upon the same problem when creating the CheckLogHeaderWorker, but didn't notice other workers had the same problem. 

A quick fix is to turn the IEnumerable into an IList or a List with .ToList() before passing it to Task.WhenAll.
