### ISSUE TITLE
Incorrent and confusing names of methods, properties

### ISSUE THREAD

**Issue by petrlicman** [equinor/witsml-explorer#2041]
**Is your feature request related to a problem? Please describe.**
Check whole solution and identify confusing and incorrect names of methods that causes worse readibility of code.
For instance ListExtensions.AsSingletonList, it does not create singleton, it is just list with one item.
Nullable vs. Optional., property containing count of items does not contain "count" in its name,

**Comment by robertbasti** [comment]
not necessary now
