### ISSUE TITLE
"Click to go back" to go back to previous page💡

### ISSUE THREAD

**Issue by asbhe** [equinor/witsml-explorer#2056]
When I click the "Click to go back" in the top left corner of my browser:
![image](https://github.com/equinor/witsml-explorer/assets/90765040/20700ba0-e067-416f-bc5f-c2f00239b0c3)
I would like to jump back to the previous page. Today nothing happens.

Blocked by Issue #2114

**Comment by janmarius** [comment]
Solved by issue #2114
