### ISSUE TITLE
💡Refresh button for (sub) objects

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2083]
Add a Refresh button for objects and sub objects, in the same way it has been done for wells/wellbores/logs.

The button should be available in the ListView and in the ContextMenu anywhere in the normal structure of the Sidebar and ListViews where a Refresh button is missing.

Example: Add a Refresh in the panel, next to Columns, Selected and Download as csv.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/0a6117a9-d37b-48e2-8810-066c8c5b4b78)

Example 2: Add a Refresh both in the panel and in the Context Menu.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/858afe88-1804-481c-9266-9877c06847eb)

**Comment by robertbasti** [comment]
needs to wait to task https://github.com/equinor/witsml-explorer/issues/1959
