### ISSUE TITLE
Improvements Plot View: Enable smoothing on plots similar to other squiggly line viewes (like Discovery Web)

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2094]
When displaying data in Plot view, just showing the values looks very messy for some curves.
We should consider to enhance the solution with an option to visualize the curves so that they look more like the log displays in other clients (e.g Disco0veryWeb, PetroVault etc...)

**Comment by eliasbruvik** [comment]
Could you provide some screenshots on how you want it to look?

**Comment by ThomasHalland** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/123538108/c5961429-973e-4218-859c-466eb3c035e8)
![image](https://github.com/equinor/witsml-explorer/assets/123538108/2d1e04b8-20b6-40e1-9385-86331bba78f9)

**Comment by ThomasHalland** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/123538108/f5a570d9-9e43-4290-a2e0-e6043a059b1d)
![image](https://github.com/equinor/witsml-explorer/assets/123538108/e8822ea7-c821-4829-833c-e3a1d512a182)
