### ISSUE TITLE
Grouping all of the actions we can perform on Log Objects👉

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2096]
The functionality should be categorized into the following groups:

refresh

Copy
Copy Log to Server
Paste Log (*)
Paste Log Curves (*)
Edit - Delete Log
Edit - Adjust Range
Edit - Splice Logs

Agents - Compare Log Header
Agents - Compare Log Data
Agents - Anazlyze Gaps
Agents - Check Log Header
Agents - Count Log Data

Import Logs from .csv

Show on Server
Query
Properties

(*) dynamic based on context.

**Comment by robertbasti** [comment]
![image](https://github.com/equinor/witsml-explorer/assets/44800029/b76bf975-a45e-470c-ac96-f888df36a85d)
