### ISSUE TITLE
Improvements Plot View: General fixes

### ISSUE THREAD

**Issue by asbhe** [equinor/witsml-explorer#2097]
General fixes - delete horizontal scale bar, and move curve name and scale value to top:
![image](https://github.com/equinor/witsml-explorer/assets/90765040/34e975be-6969-415e-8cea-a3f766b95d48)

Add fixed width to columns - scrollbar only visible if you have curves outside your view.

**Comment by eliasbruvik** [comment]
If the horizontal scale bar is removed completely, what do you expect to happen when showing a log with many mnemonics selected? Right now it shows max 12 mnemonics next to each other before scrolling is forced.
