### ISSUE TITLE
SpliceLogData - Ensure indexCurve is first in logCurveInfo

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2120]
When splicing log data, there are some logs that does not return the indexCurve as the first element in the logCurveInfo list. This can lead to errors when creating the new spliced log.

Make sure to move the element that corresponds to indexCurve as the first element in the logCurveInfo that is used internally in SpliceLogDataWorker.

**Comment by janmarius** [comment]
I suggest implementing a new method in `WorkerTools.cs` and making necessary changes in `CompareLogDataWorker.cs` as well.
