### ISSUE TITLE
🐛Multiple wells are created when copying a log to another server

### ISSUE THREAD

**Issue by janmarius** [equinor/witsml-explorer#2128]
**:bug: Describe the bug**
When copying a log to a server where the parent well does not exist, a temporary well is created in addition to the actual well.
![image](https://github.com/equinor/witsml-explorer/assets/48485965/1238ba2f-21f9-488b-999f-5b609dc97e9f)

Avoid creating temporary wells as this behavior is not recommended.

**To Reproduce**
1. Go to the source server.
2. Find a log in a well that does not exist in the target server.
3. Right click the log and select "Copy 1 log to server" and select your target server.
4. When asked "The wellUid does not exist on the target server. Do you want to copy it and its parent well? (image below), select Copy
5. Then navigate to your target server fast, and you will see the temporary well.
![image](https://github.com/equinor/witsml-explorer/assets/48485965/70dd4beb-4260-41db-a780-fa1489989796)

**Expected behavior**
Not creating a duplicated well temporarily.

**Comment by eliasbruvik** [comment]
Cannot reproduce it, and I think it was solved with the use of tanstack query instead of navigationState.
