### ISSUE TITLE
🐛 Flash of unstyled content

### ISSUE THREAD

**Issue by janmarius** [equinor/witsml-explorer#2135]
**:bug: Describe the bug**
When using the application, there are moments when the content appears incorrectly formatted before being displayed correctly.

**To Reproduce**
1. To simulate slow 3G network speed, you can throttle your network speed in your browser's developer tools, making it easier to identify this behavior.
2. Refresh the page using F5, for instance.
3. You can see that the styling is incorrectly formatted.
4. After logging in, the styling flashes one more time.

**Expected behavior**
Styling should not flicker. The team may need to explore alternative solutions for the CSS styling.

**Screenshots**
Incorrect formatting:
![image](https://github.com/equinor/witsml-explorer/assets/48485965/9669286e-be7a-449b-9e2c-04f91348a8b6)

Correct formatting:
![image](https://github.com/equinor/witsml-explorer/assets/48485965/b8c6455d-76e1-42ae-ad1a-701bf6b972b6)

**Comment by eliasbruvik** [comment]
I have only noticed this in a development environment. If we cannot reproduce it with a production build, I don't think it's worth spending time on.

**Comment by janmarius** [comment]
I think this is fairly easy to fix, and it will be valuable for developers not to see all this flickering. I came across this [issue](https://github.com/styled-components/styled-components/issues/2900) on the `styled-component`'s GitHub repo, and it seems like a common issue. I think it can be solved by moving the loading of fonts into a `global.css`, but to be able to test this, I need Equinor's CDN to be up and running again (Equinor Design System is down today). I will assign myself to the task and see if the quick fix works.
