### ISSUE TITLE
Clean up index.tsx

### ISSUE THREAD

**Issue by janmarius** [equinor/witsml-explorer#2137]
**Is your feature request related to a problem? Please describe.**
There is unnecessary logic in `index.tsx`. Initial values for operation states should be set in the operation context provider.

**Describe the solution you'd like**
The logic in the image is only executed once to set initial values from local storage. This logic should be moved into the context provider for the operation state.
![image](https://github.com/equinor/witsml-explorer/assets/48485965/daf5795b-e054-45d7-9654-b99964325eed)

**Comment by GajendraR** [comment]
can i work on this and can you guide me ?

**Comment by janmarius** [comment]
Feel free to work on a task if nobody has assigned themselves to it. Can you tell me what kind of guidance you need?

**Comment by janmarius** [comment]
> can i work on this and can you guide me ?

Feel free to work on a task if nobody has assigned themselves to it. Can you tell me what kind of guidance you need?

**Comment by janmarius** [comment]
The logic has been moved to `Root.tsx`. Any necessary refactoring should be performed in this file.
