### ISSUE TITLE
Log: Show on Server need to open the contecnt of the Content View on the target server (not just show a list of all logs)💡

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2153]
Today when you rightclick on a Log, and select show on server, WEx does not open the log on the target server, it only shows a list of the logs available on the target server.

This shall be changed so that this feature will open THE ACTUAL Content View that the user has selected on the source server.
In this screenshot this feature should have opened the Downhole Logging Data - Depth RT logs in the new tab, not as today where it only shows the list of available depth logs....

![image](https://github.com/equinor/witsml-explorer/assets/123538108/d73359e7-e7c4-4a20-b275-8edf2fe6ce67)

Example 1  : Opening a content view with a list of available Log Curves.

In the example below, we are starting with a list of log curves, and when clicking on "Show on Server...." we want to see the same view from the target server. Please note that in this case we want to open all the curves available in the Target server, even if there are fewer / more curves on the target server than on the source server.

![image](https://github.com/equinor/witsml-explorer/assets/123538108/91a6f144-83de-42f0-b4c8-75abfdcd519e)

Example 2 : Opening a Selected Content View Data value set.

In this example below, we have opened a subset of all the available Log Curves and listed the data values in the Content View. Here we should be able to right-click somewhere in the content window and select Show on .....<server> 
You will then get a small popup window there you can select two options (option 1 is default):

1. Full data range available      // this will open the rull range of data points even if the source  data content nterval is smaller
2. Selected data range interval  // this will only open the specific interval as spesified in the source data content window

OK / CANCEL

![image](https://github.com/equinor/witsml-explorer/assets/123538108/425d5806-5a59-4153-bcdd-f45b3f78de5a)

**Comment by janmarius** [comment]
"Example 1 : Opening a content view with a list of available Log Curves.": This example will be resolved once the new routing is merged in #2114

"Example 2 : Opening a Selected Content View Data value set.": Example 2 should be done in this issue.
