### ISSUE TITLE
Enhancement to Download to CSV

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2155]
When you have made a selection of curves in a log (including the edge case that you have selected all curves), then you click the "Download all as .csv" button (already implemented). You will then get a popup window with options:

For the selected Log Curves:
1. Download all data (not only first 10000 as displayed)
2. Download the interval of data between the start and end index in the Content Window
3. Download selected index values 

The user will select from these 3 options and hit OK or Cancel button.

**Comment by asbhe** [comment]
Download options:
1. Download shown interval
2. Download selected
3. Download all data (minIndex to maxIndex for all listed mnemonics, max 5'000'000 datapoints)
