### ISSUE TITLE
🐛Sometimes when using CTRL + F in WITSML Explorer it does not find mnemonics that are present

### ISSUE THREAD

**Issue by ssf93** [equinor/witsml-explorer#2157]
Sometimes when using CTRL + F in the content window it does not find mnemonics that are present in the content window. Unsure what causes it to find data in the window. 

It might be that clicking certain places in the window causes it(?)

**Comment by eliasbruvik** [comment]
Does this happen for mnemonics that are visible? As the table is virtualized, only a few rows above and below what you actually see are rendered. So CTRL + F would not find any mnemonics that are not rendered.

**Comment by ssf93** [comment]
It happened when I had the list visible both with and without scrolling. I will try to re-create the bug so I can give more detail

**Comment by eliasbruvik** [comment]
Are you able to reproduce this?

**Comment by eliasbruvik** [comment]
Closing this as stale. Create a new issue with a feature request if you want to be able to search/filter for values in a column.
