### ISSUE TITLE
Parent menu items for nested items are deactivated when they should be active🐛

### ISSUE THREAD

**Issue by janmarius** [equinor/witsml-explorer#2165]
**:bug: Describe the bug**
Parent menu items for nested items are deactivated when they should be active; in the context menu below, the "edit" option should be active (white, not gray).

![image](https://github.com/equinor/witsml-explorer/assets/48485965/52b1819e-fc7e-4e0a-8caf-4a2e8c3817c8)

**Comment by janmarius** [comment]
This issue is a duplicate of #2159 and should be deleted.

**Comment by eliasbruvik** [comment]
#2163 fixed it for the Edit button, but the servers under Show on server is still enabled even though multiple logs are selected. This also needs to be fixed.
