### ISSUE TITLE
📘Document how to access nuget pkg 

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#218]
**Documentation Is:📘 **

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

**Please Explain in Detail**

The procedure to get access to the nuget pkg  is not obvious and should probably be documentet somehow
Details in discussion [Discussion # 212](https://github.com/equinor/witsml-explorer/discussions/212)

**Your Proposal for Changes**

Outline the steps to ease onboarding

**Comment by marmid74** [comment]
Please submit a pull request to solve this issue.
