### ISSUE TITLE
🐛Syncing 1 curve from HAL to Sitecom PROD is "Started" in Jobs view and does not finish

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2190]
When I sync BITZ (1 depth curve) from HAL RTS to SITECOM PROD, it remains as "started" in the Jobs pane, even though I see that the job seems to have completed.

![image](https://github.com/equinor/witsml-explorer/assets/123538108/6b56d3f3-0c51-4346-bc97-b2d4cdf0d108)

**Comment by janmarius** [comment]
Can @ssf93, @asbhe or @ThomasHalland confirm if the bug still exists? I believe it was resolved while addressing a separate issue.
