### ISSUE TITLE
Problem with Copy Curve between servers if you include INDEX curve💡

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2191]
In this case WEx tries to delete/insert the index curve which results in an error. 
This need to be fixed.

**Comment by eliasbruvik** [comment]
My first thought was that we could simply skip copying the index curve as the target server already should have an index curve. However, even though the index curve exists, and there is no data to copy for the index curve specifically, we still need to copy other properties of the index curve like unit, curveDescription etc. 

#2205 also addresses copying the other properties, but in another setting.

**Comment by eliasbruvik** [comment]
Fixed by #2221
