### ISSUE TITLE
Create a desktop Edition of Witsml Explorer with simple non-technical installation

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2194]
As a casual WITSML user, I want to be able to install WITSML Explorer on my desktop client with a simple installation which does not require any "IT knowledge", so that I can afterwards add my WITSML servers and everything will be running on my desktop,

Requirements:
- no need for Azure account,
- simple installation
- When user register WITSML databases, they shall be stored and available to the user next time he runs the application,
- User shall be able to add / remove WITSML stores,
- GUI shall be the same as the normal version (running in the browser)

**Comment by janmarius** [comment]
During one of the stand-up meetings, it was brought up that code signing may be required for Equinor users. Adjustments might also be necessary for non-Equinor users. It's also important to keep in mind potential issues with firewalls and ensure that the executable is enterprise-friendly if necessary.
