### ISSUE TITLE
Update search view after batch updating

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2195]
After batch updating an object from the search view, I want the view to refresh the search. 

This only applies when updating a property that shows in the search view, like `name`.

**Comment by robertbasti** [comment]
could you please describe it more details and add some screenshots?

**Comment by eliasbruvik** [comment]
If you select to search for Logs or Rigs (or something else that opens the ObjectSearchListView.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/a73defd5-2bbf-43df-a40f-509817f2b8be)

Then right click on a couple, and select Batch Update.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/b10b578d-5f51-4cc2-b9ca-145a0d758ae4)

Edit the name, and click save. After the batch update is complete, the items (names) in the search view should be updated.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/4831230b-c87b-43ba-9f07-160ad651e412)

Currently in our application, when we start a job in the API that we want to update something in the frontend, we return a RefreshAction. However, the `RefreshHandler.tsx` is not configured to update the search. The data from the search is placed in the `searchResults` variable in the `Filter` object, which is used in ObjectSearchListView through FilterContext.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/2a6f98e2-8010-4eb8-8b78-437472fb042b)

The solution must find a way to let the RefreshHandler know that it's the search view that should be updated, and then update the searchResults by updating the value in the FilterContext accordingly.

Note that the ObjectSearchListView does not fetch all properties for the objects, so we only need to refresh if any of the shown properties are updated. If let's say runNumber is changed in the batchUpdate, but not the name, refreshing the search is unnecessary.

**Comment by eliasbruvik** [comment]
Fixed by #2322
