### ISSUE TITLE
Investigate possibility of setting a fixed global culture in the API

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2200]
Currently, our API encounters challenges related to handling different cultures, leading to inconsistencies in data formatting across various environments. Instead of having to specify InvariantCulture every time you try to parse a value, we should look into overwriting the culture of the host with a fixed culture that should be used throughout the application.

Investigate if such a solution is possible, and any implications it may have.

**Comment by robertbasti** [comment]
is that related only to API part in C#?

**Comment by eliasbruvik** [comment]
Correct, it's only related to the API.

**Comment by eliasbruvik** [comment]
Added `High Priority` as we can get a lot of bugs if forget to account for culture now that the API can run with a lot of different cultures with the Desktop edition.
