### ISSUE TITLE
Delete empty mnemonics also available on Logs💡

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2203]
Today we have an option to delete empty mnemonics when right clicking on a wellbore, and I also need this option on the Log level. 
So: Right click on a Log --> have the option available in the popup menu similar to the setup when doing this operation on the Wellbore level. 

PS: When doing it at the log level it will only delete empty mnemonics on the selected log

**Comment by eliasbruvik** [comment]
This issue was fixed by #2207
