### ISSUE TITLE
🐛 Deleting curves within a log with index curve marked goes to "failed"

### ISSUE THREAD

**Issue by ssf93** [equinor/witsml-explorer#2204]
If I select all curves in a log and want to delete data from X depth to Y depth it will go to status "Failed" immediately due to having selected the index curve + the other mnemonics.

**Comment by eliasbruvik** [comment]
The index curve should be skipped even though it is selected. A log needs to have a index curve, so deleting it does not make sense.

Suggested fix:
Filter away the index curve before ordering the job.
