### ISSUE TITLE
Optimize refreshing of single objects

### ISSUE THREAD

**Issue by janmarius** [equinor/witsml-explorer#2260]
As we are using Tanstack Query to fetch data, we can simply invalidate the queries to ensure that the objects are re-fetched when used. However, if we need to refresh a single well/wellbore/object (either manually by clicking refresh, or with a RefreshAction from the API), we currently invalidate the query of the whole list. If we instead invalidate only the object, it would not actually be re-fetched until the single-item query is used. This would mean that the list would not be updated with that item. 

Investigate if it’s possible to force a re-fetch even when it’s not used, or if there are other ways of optimizing refreshing of single objects. Also consider if the benefit of the optimization outweighs the increased complexity of the new solution. It might be better to keep it the way it is today.

An optimization should be implemented for well/wells, wellbore/wellbores and object/objects.

**Comment by robertbasti** [comment]
a discussion with Elias needed
