### ISSUE TITLE
Filtering normal list views while searching/filtering

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2272]
Should normal list views be filtered while searching? Currently the sidebar is filtered, but not the other views. If we want the list views to be filtered, should it also filter when searching for objects (after navigating away from the search view)? What about the filters like “only show growing logs” and “hide inactive wells/wellbores”?

As seen below, the sidebar is filtered, but not the list view.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/6df199bc-8494-44e7-853d-066d813d0ff5)

**Comment by robertbasti** [comment]
needs explanation from Elias what exactly is meant, discuss with Sebastian if relevant

**Comment by eliasbruvik** [comment]
Closing as this has not been requested or mentioned so it is probably fine to leave it as is.
