### ISSUE TITLE
💡Add internal metrics showing usage of Witsml library

### ISSUE THREAD

**Issue by lindsve** [equinor/witsml-explorer#2290]
It would be really interesting to have metrics showing the usage of the Witsml library. Interesting metrics would be request durations and number of active requests.

.NET 8 introduced native libraries for OpenTelemetry, which is ideal for this purpose since it does not care what format metrics are exported to and can be used with both Azure AppInsight, Prometheus, etc.

I propose an implementation that uses these libraries to expose these metrics

**Comment by eliasbruvik** [comment]
Completed by #2291
