### ISSUE TITLE
👉 Visualize Active WELL / WELLBORE

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#232]
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #177 

It is important for users to quickly and easily get an overview over which WELLS, WELLBORES and LOGS are active.

**Describe the solution you'd like**
A visual indicator similar to what is seen in the picture: 
🟢 A green circle indicates the object or an object lower in the hierarchy is active. 
⚪ An empty circle indicates the object and no objects lower in the hierarchy are active.

Using a similar approach to what exists in current solutions makes it easier for users of WITSML Explorer to recognise the functionality.

![image](https://user-images.githubusercontent.com/1553016/109810949-83677c00-7c2a-11eb-88ab-8e4046cc4ee4.png)

**Describe alternatives you've considered**
Currently no alternatives, but open to suggestions

**Additional context**
The relevant WITSML data comes from the **isActive** tag.
```XML
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<wellbores version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series">
	<wellbore uidWell=" uid=">
		<nameWell />
		<name />
		<isActive>true</isActive>
	</wellbore>
</wellbores>
```

**Comment by marmid74** [comment]
We need to check with our UI designer how to represent "isActive" in the sidebar, if this should be a green/grey circle or another type of icon.

As a start you can implement with green circle, and I will notify you if we decide that there should be used another icon not vulnerable for colour blindness (universal design requirement).

**Comment by marmid74** [comment]
**Agreed in meeting (Equinor/KongbergDigital/AkerBP) :**

- Ensure that the open wellbore (return all wellbores) query returns the isActive property, and filter in frontend when Filter on active is set.
- Some witsml servers do not set isActive property automatically. So on some witsml-servers might show incorrect value on isMissing.
