### ISSUE TITLE
👉 Filter on Active WELLBORE

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#233]
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #177 

Users should be able to filter on **Active Wells** to more easily work only on active WELLS / WELLBORES.

**Describe the solution you'd like**
A filter option or check box similar to what is seen in the picture.

When the filter is applied, only **Active Wells** are displayed.

Using a similar approach to what exists in current solutions makes it easier for users of WITSML Explorer to recognise the functionality.

![image](https://user-images.githubusercontent.com/1553016/109812873-e528e580-7c2c-11eb-9ca4-84c9d446a3e3.png)

**Describe alternatives you've considered**
Currently no alternatives, but open to suggestions

**Additional context**
The relevant WITSML data comes from the isActive tag.

```<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<wellbores version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series">
	<wellbore uidWell=" uid=">
		<nameWell />
		<name />
		<isActive>true</isActive>
	</wellbore>
</wellbores>
```

**Comment by marmid74** [comment]
Will discuss with UI designer asap. Will notify you.
