### ISSUE TITLE
👉 Visualize Growing (WELL / WELLBORE) LOG

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#234]
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #177 

It's important for users to quickly and easily get an overview over which WELLS and WELLBORES contain **Growing Logs**.

**Describe the solution you'd like**
**Bolding** WELLS and WELLBORES can be done to indicate if they contain growing logs.

**Describe alternatives you've considered**
Currently no alternatives, but open to suggestions

**Additional context**
The relevant WITSML data comes from the **objectGrowing** tag.

```XML
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<logs version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series">
	<log uidWell=" uidWellbore=" uid=">
		<nameWell />
		<nameWellbore />
		<name />
		<objectGrowing>true</objectGrowing>
	</log>
</logs>
```

**Comment by marmid74** [comment]
Will discuss with UI designer asap, will notify you.

**Comment by marmid74** [comment]
**Challenge:** Only SiteCom WitsmlServers support open query (no uid well , no uidwellbore) on log object. So the community need to come up with a proposal how to enable functionality not mandatory in witsml standard, but allowed, and still ensure that WE works on all types of Witsml servers.

What is possible at time beeing: In context of a wellbore, objectGrowing is returned.

**Discussion to be raised in community:** How to support proprietary features
