### ISSUE TITLE
👉 Filter on Growing LOG

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#235]
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #177

Users should be able to filter on **Growing Logs** to more easily work only on WELLS / WELLBORES containing growing logs.

**Describe the solution you'd like**
A filter option or check box where the user can check to filter on **Growing Logs**.

When the filter is applied, only **Growing Logs** are displayed.

**Describe alternatives you've considered**
Currently no alternatives, but open to suggestions

**Additional context**
The relevant WITSML data comes from the **objectGrowing** tag.

```XML
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<logs version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series">
	<log uidWell=" uidWellbore=" uid=">
		<nameWell />
		<nameWellbore />
		<name />
		<objectGrowing>true</objectGrowing>
	</log>
</logs>
```

**Comment by marmid74** [comment]
Will discuss with UI designer asap how this should look like. Will notify you.

**Comment by marmid74** [comment]
Challenge: Only SiteCom WitsmlServers support open query (no uid well , no uidwellbore) on log object. So the community need to come up with a proposal how to enable functionality not mandatory in witsml standard, but allowed, and still ensure that WE works on all types of Witsml servers.

What is possible at time beeing: In context of a wellbore, objectGrowing is returned.

Discussion to be raised in community: How to support proprietary features

**Comment by Renani** [comment]
Hi, 
Activewellbore is witsml 1.4.1.1 only attribute as well. 

On the topic of "How to support proprietary features" consider Strategy pattern and allow advanced end-users to switch between strategies for servers if one does not match.
