### ISSUE TITLE
Multiple Logs with the same name shall be collapsed in TREE structure, and it shall be possible to expand / collapse additional level

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2358]
If you have 2 or more Logs with the same name, they shall only show as one entry in the list of available logs, with an expand icon available to indicate that there are more than one Log with this name. After the Log name, the word (multiple) shall be put in the paranthesis where we normally place the run number (see example below).

![image](https://github.com/equinor/witsml-explorer/assets/123538108/06185a9c-c6b6-4a2c-8abb-a8f185417931)

**Comment by eliasbruvik** [comment]
Fixed by #2408
