### ISSUE TITLE
👉 Visualise Live Objects

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#236]
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #177 

It is important for users to quickly and easily see which WELLS / WELLBORES and LOGS which are currently live streaming so they can get an overview and work on operations with live data.

**Describe the solution you'd like**
A visual indicator next to the objects to indicate they are currently live streaming, similar to what is seen in the picture below. 

When a log object is live streaming, the relevant wellbore and well should also be indicated in the same way.

![image](https://user-images.githubusercontent.com/1553016/109824979-a77e8980-7c39-11eb-8651-24082441f2cf.png)

**Describe alternatives you've considered**
Currently no alternatives, but open to suggestions

**Additional context**
---

**Comment by marmid74** [comment]
Will discuss with UI designer asap, will notify you.
