### ISSUE TITLE
🐛When changing TimeZone in Settings - the search start and end index should also be set to search in the same time sone.

### ISSUE THREAD

**Issue by ThomasHalland** [equinor/witsml-explorer#2411]
![image](https://github.com/equinor/witsml-explorer/assets/123538108/6b4dd9c2-52cb-406e-bdaf-d5946cda76c5)

Task: Make a change so that also the start and end index search boxes is in the same Time Zone as selected in the Settings

**Comment by eliasbruvik** [comment]
Completed by #2415
