### ISSUE TITLE
🐛Timepicker not working as inteden

### ISSUE THREAD

**Issue by asbhe** [equinor/witsml-explorer#2526]
**:bug: Describe the bug**
When selecting a date when viewing a curve, I am not able to select the date I want. It does not work when writing with keyboard, and it does not work with the datepicker.

**To Reproduce**
1. Go to a log, select a few curves, choose e.g. "last 6 hours".
2. Click on the "End Index" timepicker and try to change the date.
3. Try to write the date/time you want instead

**Expected behavior**
You are able to select the time you want.

**Screenshots**
![image](https://github.com/user-attachments/assets/efbf3c30-697c-41a4-8e56-b18229a2d1d7)

**Additional context**
Start Index looks to be working as expected. I only struggle with End Index.

**Comment by robertbasti** [comment]
we cannot reproduce the issue

**Comment by robertbasti** [comment]
we cannot reproduce the issue
