### ISSUE TITLE
Ultra compact bugs🐛

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2576]
Some minor visual bugs in the ultra compact mode. If more shows up before these have been fixed, they will be added to this list.

Buttons misaligned while logging in:
![Image](https://github.com/user-attachments/assets/36eab06d-07d0-4304-91b4-200ec91c1c87)

Breadcrumbs:
![Image](https://github.com/user-attachments/assets/ad6dffeb-f94f-4be5-afc0-e1e7d3604064)

Warning in the console when opening the front page (and a few other similar warnings about isCompact on other pages):
![Image](https://github.com/user-attachments/assets/0ad845ad-e0c1-432b-9509-b492f936dcae)

Warning in the console when clicking "Pick template" in the query view:
![Image](https://github.com/user-attachments/assets/d16dd5ff-bac3-4a6f-a231-7b4a6041479e)

**Comment by robertbasti** [comment]
The first issue - It's only when it's loading after clicking "Login"
