### ISSUE TITLE
Progress stuck after cancelling a job within the modal🐛

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2633]
When I clicked cancel, I would expect the modal to either close, or to show that the job was cancelled once the cancellation was complete. Instead, it remained stuck at the same percentage.
![Image](https://github.com/user-attachments/assets/3b2fea93-434b-4fd4-a6fb-c62efa074b46)

**Comment by robertbasti** [comment]
is that related to all "long" processes or only to one particular ?

**Comment by robertbasti** [comment]
downloading log data
