### ISSUE TITLE
🐛Unable to connect to Equinor Sitecom Acceptance

### ISSUE THREAD

**Issue by lindsve** [equinor/witsml-explorer#274]
**:bug: Describe the bug**
Unable to connect to Sitecom Acceptance (QA)

**To Reproduce**
1. Select "Equinor Sitecom Acceptance" as the server to open
2. Enter credentials and click on 'Save'
3. See error `Unexpected token < in JSON at position 0`

**Expected behavior**
Modal dialog should close and list of wells in Sitecom QA should be visible

**Screenshots**
![Skjermbilde 2021-03-18 kl  10 24 20](https://user-images.githubusercontent.com/159861/111602901-1cbe9280-87d4-11eb-8cb9-beedd077ae2f.png)

**Comment by steinsiv** [comment]
Firewall setup causing SiteCom Acceptance to be unaccessible has been fixed 24. March
