### ISSUE TITLE
🐛 Quickly clicking two unexpanded wellbores can cause logs data to not be retrieved correctly, causing a crash

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#298]
**:bug: Describe the bug**
Sometimes, when quickly clicking on two wellbores where data has not yet been retrieved, can cause log data to not be retrieved correctly. When expanding the logs of one of the wellbores, if there is no log data, the application will crash due to a null-reference

**To Reproduce**
1. Find a well with two wellbores.
2. Click on both wellbores in the sidebar in quick succession.
3. Open logs.
4. Sometimes the application crashes

**Expected behavior**
Log data is retrieved correctly and there is no crash.

**Screenshots**
![CrashOnDoubleRetrieve](https://user-images.githubusercontent.com/1553016/112503249-0e9be380-8d8b-11eb-960d-05ec0bbe1006.gif)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by marmid74** [comment]
Please submit a pull request to solve this issue.

**Comment by ThomasHalland** [comment]
Can we still reproduce this, or is it maybe solved ?

**Comment by janburak** [comment]
> Can we still reproduce this, or is it maybe solved ?

Still an issue. Will be fixed as part of #1933.
