### ISSUE TITLE
Feature request: List Risk objects

### ISSUE THREAD

**Issue by lindsve** [equinor/witsml-explorer#30]
This would be on the same level in the hierarchy as `Logs`, `Rigs`, `Trajectories`.

**Comment by steinsiv** [comment]
This is now supported through the following PRs

https://github.com/equinor/witsml-explorer/pull/1310
https://github.com/equinor/witsml-explorer/pull/1328
https://github.com/equinor/witsml-explorer/pull/1336
https://github.com/equinor/witsml-explorer/pull/1340

Closing
