### ISSUE TITLE
Improve performance of onClick events.

### ISSUE THREAD

**Issue by aszalos-roland** [equinor/witsml-explorer#348]
**Is your feature request related to a problem? Please describe.**
It takes too long (4 secs or more) to expand tree elements.

**Describe the solution you'd like**
Add useCallback to onClick events. I've tried using it and it significantly increased performance.

**Describe alternatives you've considered**
Open to alternatives, but I think this is a good solution.

**Additional context**
Before:
![image](https://user-images.githubusercontent.com/76997928/115697174-9b729680-a363-11eb-9f07-cd643d86bccc.png)
Proposal:
![image](https://user-images.githubusercontent.com/76997928/115697037-7e3dc800-a363-11eb-9128-0518b23c67c0.png)

**Comment by marmid74** [comment]
Good proposal. Please submit a PR 👍

**Comment by ThomasHalland** [comment]
Is this completed, or still a potential performance improver ?

**Comment by janburak** [comment]
I tested it and did not notice any improvement with 1000 wells in the sidebar. Likely one would have to virtualize the sidebar to improve performance ref #1913.
