### ISSUE TITLE
Refactoring Query code

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#350]
**Refactoring code that generate Witsml DTOs**

When instantiating `Witsml.Data` objects to be used in Witsml server queries, duplicate implementations exists within both `Witsml` and `Witsml.Api` project, which might be confusing. 

e.g. 

**Witsml.Api:** `WitsmlExplorer.Api/Workers/BatchModifyWellWorker.cs` , `WitsmlExplorer.Api/Workers/ModifyWellWorker.cs`
```csharp        
private static WitsmlWells CreateUpdateQuery(Well well)
        {
            return new WitsmlWells
            {
                Wells = new WitsmlWell
                {
                    Uid = well.Uid,
                    Name = well.Name,
                    Field = well.Field,
                    TimeZone = well.TimeZone,
                    Country = well.Country,
                    Operator = well.Operator
                }.AsSingletonList()
            };
        }
```

**Witsml:** `Src/Witsml/Query/WellboreQueries.cs`
```csharp
        public static WitsmlWellbores QueryByUid(string wellUid, string wellboreUid)
        {
            return new WitsmlWellbores
            {
                Wellbores = new WitsmlWellbore
                {
                    Uid = wellboreUid,
                    UidWell = wellUid,
                    Name = "",
                    NameWell = ""
                }.AsSingletonList()
            };
        }

        public static WitsmlWellbores UpdateWellboreQuery(string wellUid, string wellboreUid)
        {
            return new WitsmlWellbores
            {
                Wellbores = new WitsmlWellbore
                {
                    Uid = wellboreUid,
                    UidWell = wellUid,
                    Name = ""
                }.AsSingletonList()
            };
        }

        public static WitsmlWellbores DeleteWellboreQuery(string wellUid, string wellboreUid)
        {
            return new WitsmlWellbores
            {
                Wellbores = new WitsmlWellbore
                {
                    Uid = wellboreUid,
                    UidWell = wellUid
                }.AsSingletonList()
            };
        }
```

Imperative naming like `delete` and `update` is in this case not reflecting accurately what the method actually does.

**Suggestion**
Refactor and revise query naming and implementations to better reflect what is being returned.

**Comment by kdi-chandra** [comment]
I see that, If we move 'Query' folder from Witsml to Witsml.Api, Then it helps in removing the duplicate code and maintaining the query construction for all operations (get, update, delete...)  in one place.

**Comment by marmid74** [comment]
@steinsiv , @kdi-chandra , @HakonHesselberg will discuss how to solve this task.

**Comment by stigrus** [comment]
Please include Me @stigrus and @lindsve in this discussion

**Comment by lindsve** [comment]
I've mentioned this earlier to @steinsiv, but the current implementation of having query implementations in the `Witsml` library might be both confusing and wrong. These constructs are not queries themselves, just datastructures of what should be queried upon or fetched, and the usage very much depends on the second parameter to the `GetFromStore` method (OptionsIn).

These constructs depends very much on how they are used and as such might be better to be completely moved from `Witsml` to the API project. This makes it a bit easier to add support for new types as well, since the library won't have any responsibility on how they are used

**Comment by kdi-chandra** [comment]
After discussion, it is concluded that we move 'Query' folder from Witsml project to WitsmlExplorer.Api project and use logically appropriate names for the classes and methods
