### ISSUE TITLE
👉 When the user tries to open more than 200 mnemonics the request fails

### ISSUE THREAD

**Issue by aszalos-roland** [equinor/witsml-explorer#365]
**👉 Is your feature request related to a problem? Please describe.**
We allow the users to select all the mnemonics, but the get request fails when the URL is more than 2048 characters.
Related stories: #173, any story that relies on reading LogData

**Describe the solution you'd like**
Write an alternative POST endpoint, so we can send the mnemonics in the request body if the URL would be too long.

**Describe alternatives you've considered**
Not allowing the user to select that many mnemonics.

**Additional context**
Screenshot of the problem:
![too_many_mnemonics](https://user-images.githubusercontent.com/76997928/116986116-b29f7580-accd-11eb-8a3a-e75d5baa5039.png)

**Comment by steinsiv** [comment]
It seems like this exact case Is related to CORS settings? 
I guess we do not want to open up for `access-control-allow-origin: *`

**Comment by aszalos-roland** [comment]
> It seems like this exact case Is related to CORS settings?
> I guess we do not want to open up for `access-control-allow-origin: *`

it's not a cors related issue I can reach the endpoint with less mnemonics selected, idk why it returns a cors error, maybe because it's a preflighted request and the server determined in this case that the request is not safe to send so it returned a cors error

**Comment by marmid74** [comment]
From description above this seems both as a bug and a feature enhancement.
Please submit a pull request to solve this issue.
