### ISSUE TITLE
🐛 Sorting is wrong in the mnemonic ContentTable

### ISSUE THREAD

**Issue by aszalos-roland** [equinor/witsml-explorer#398]
**:bug: Describe the bug**
Sorting a column on the ContentTable uses an alphabetical sort order even when the column contains numbers. This seems like inappropriate behaviour to me.

**To Reproduce**
1. Go to a depth log
2. Sort by MinIndex
3. The column is not sorted as expected

**Expected behavior**
Columns with numerical data are sorted by using a numeric sort order.

**Screenshots**

Sort by MinIndex Asc:
![sorting_is_wrong](https://user-images.githubusercontent.com/76997928/118120668-846a1600-b3f0-11eb-984d-71ae2334e51d.png)

Sort by MinIndex Desc:
![sorting_is_wrong_2](https://user-images.githubusercontent.com/76997928/118120685-8df37e00-b3f0-11eb-9aaf-ae8e67c4ab65.png)

**Desktop (please complete the following information):**
- any os, any browser
- found in main branch 

**Smartphone (please complete the following information):**
- any browser, any device
- found in main branch 

**Additional context**
no additional context

**Comment by marmid74** [comment]
Not able to reproduce the error on our data/witsml-server, so this is strange. @kdi-chandra, @HakonHesselberg are you able to reproduce this error on your data/witsml servers?

**Comment by kdi-chandra** [comment]
I am not able to reproduce; Working as expected

**Comment by HakonHesselberg** [comment]
Reproduces with me using Haliburton test server

Doesn't reproduce everywhere, since it sorts some of it correctly in chunks.

It sorts correctly until halfway, then sorts the other half correctly.

![image](https://user-images.githubusercontent.com/1553016/118813056-0ce42d00-b8af-11eb-89bf-6eccdb416214.png)

**Comment by HakonHesselberg** [comment]
Able to repro in other columns as well:
![image](https://user-images.githubusercontent.com/1553016/118814805-d3142600-b8b0-11eb-94e5-7587b08fcd8a.png)
