### ISSUE TITLE
👉 Enable environment variables to support deployment causes pathing issues

### ISSUE THREAD

**Issue by aszalos-roland** [equinor/witsml-explorer#421]
**👉 Is your feature request related to a problem? Please describe.**
When #364 was merged back it caused pathing issues on the development side.

**Describe the solution you'd like**
Fix the pathing issues.

**Additional context**
Issue:
![image](https://user-images.githubusercontent.com/76997928/119666253-8216ab80-be35-11eb-9cc6-8851913d26eb.png)

As seen in the picture there are more trailing slashes, than necessary.

**Comment by kdi-chandra** [comment]
This issue is fixed by PR #423
