### ISSUE TITLE
🐛  Duplicate LogData keys on the WITSML Server

### ISSUE THREAD

**Issue by aszalos-roland** [equinor/witsml-explorer#439]
**👉 Is your feature request related to a problem? Please describe.**
Related to #174 because we can't insert duplicate keys.
Also related to #173 because it exports duplicate rows as well and since we can't import data with duplicate keys this becomes a problem.

**Describe the solution you'd like**
Looks like the WITSML server is wrong here, we could try fixing that.

**Describe alternatives you've considered**
Merge data with the same keys

**Additional context**
Response from the https://sitecom.intellifield.no/Store/WITSML server:
![image](https://user-images.githubusercontent.com/76997928/120777570-b66d2480-c525-11eb-8ce1-6150bd337ae7.png)
Duplicates can be seen in the image above.

The above response is data from the following log:
![image](https://user-images.githubusercontent.com/76997928/120777731-e3213c00-c525-11eb-9426-e1fee14789d9.png)

The UI also can't handle the duplicated keys as seen in the following image:
This part of bug issue is now moved to #655 
![image](https://user-images.githubusercontent.com/76997928/120777912-182d8e80-c526-11eb-8616-f8f348436930.png)

**Comment by petrlicman** [comment]
Postponed because cannot be properly fixed on WITSML explorer side. Old issue, did not occur for long time.

**Comment by eliasbruvik** [comment]
Closing this as it's a WITSML server fault, not Witsml Explorer.
