### ISSUE TITLE
User story: Auto refresh on active logs

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#478]
### User story: Auto refresh on active logs  ###

As a User I want to have an auto refresh feature to view new incoming logdata on active logs

**Sketches**
Time based logs
![image](https://user-images.githubusercontent.com/22211376/122216927-36dc3f80-cead-11eb-8754-7ea2a1f7b003.png)
Depth based logs
![image](https://user-images.githubusercontent.com/22211376/122216968-4196d480-cead-11eb-9cfa-523cc1b30ee9.png)

### Acceptance criteria ###
- [ ] [describe criteria]
- [ ] [describe criteria]

Also, here are a few points that need to be addressed:
- [ ] [describe Constraint]
- [ ] [describe Constraint ]

### Resources ###

-  Lead resource: AkerBP
-  Contributors: [list names/company]

**Comment by eliasbruvik** [comment]
Will be covered by the more recently groomed #1899 (see comments).

**Comment by eliasbruvik** [comment]
Implemented in #2050.
