### ISSUE TITLE
🐛 Update request missing mandatory parameters

### ISSUE THREAD

**Issue by Pascal62223** [equinor/witsml-explorer#480]
**:bug: Describe the bug**
When doing an update on any supported object ( well , wellbore...) request body should include `<OptionsIn/>` and `<CapabilitiesIn/>`.
These two parameters are marked as mandatory by the WITSML 1.4.1.1 API specification, even if most of existing servers to accommodate for these parameters to be omitted (server handle if omitted then consider them empty).
However some servers are more strict regards to the specification and throw exception in such type of request.

**To Reproduce**
1. Open Witsml Explorer
2. Select wellbore property and change the name
3. Observe the request body. Missing mandatory parameter

**Expected behavior**
Request must include `<OptionsIn/>` and `<CapabilitiesIn/>` in body to align with specification, and not rely on server interpretation.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Not relevant

**Smartphone (please complete the following information):**
 - Not tested on mobile, but same error as it is a request content issue

**Additional context**

**Comment by lindsve** [comment]
Updated the description with code tags so that the properties missing are actually displayed in the issue text

**Comment by lindsve** [comment]
I believe `OptionsIn` are always specified since we specifically set up the witsml client for this.

But `CapabilitiesIn` is not used by this library

**Comment by Pascal62223** [comment]
Great @lindsve . Thnaks.
