### ISSUE TITLE
💡 Create missing curves/mnemonic when importing CSV file 

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#499]
related to user story : #554 

**💡 Is your feature request related to a problem? Please describe.**
The import log functionality import curve values into a log only if the mnemonics already exists.

**Describe the solution you'd like**
Create missing curves/mnemonic when importing CSV file will make creating and importing test data to an empty log possible.

**Describe alternatives you've considered**

**Additional context**
See #494

**Comment by janburak** [comment]
TypeLogData is required when creating LogCurveInfo. One would need to figure out how to deteremine what TypeLogData each LogCurveInfo should be initialized with.

Edit: TypeLogData can be initially assumed to always be double. Need to show information to the user that only double data is supported.

**Comment by janburak** [comment]
Also add an example of data format when trying to import a csv file, such as:
Depth[m],Mnemonic1[rpm],Mnemonic2[m]
195.99,,2500
196.00,1,2501
