### ISSUE TITLE
👉  Constraint checking `CSV import log` functionality

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#500]
related to user story : #554 

**👉 Is your feature request related to a problem? Please describe.**
Constraint checking CSV import log to be able to import large files

**Describe the solution you'd like**
Find a way to determine the maximum amount of rows that can be sent to the WITSML server then pass that amount to the CreateImportQueries method

**Describe alternatives you've considered**

**Additional context**
See source code [/Src/WitsmlExplorer.Api/Workers/ImportLogDataWorker.cs#L73](https://github.com/equinor/witsml-explorer/blob/b4d6dd08b79c293a36ee2f69a5c8a5312feec85b/Src/WitsmlExplorer.Api/Workers/ImportLogDataWorker.cs#L73) 
See Issue #501

**Comment by eliasbruvik** [comment]
This should be determined by maxDataNodes and maxDataPoints once #1957 is implemented. All of the data should be sent, but in batches that is within the max size.

There is also a frontend error when trying to import a file that is too large (>30 000 000 bytes) that needs to be handled.

**Comment by eliasbruvik** [comment]
Already implemented by #2499. We can create a new issue for files over 30 000 000 bytes later if requested.
