### ISSUE TITLE
👉 Progress feedback on `CSV import log` functionality 

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#501]
related to user story : #554 

**👉 Is your feature request related to a problem? Please describe.**
When importing large files, give user progress feedback through the already established websocket

**Describe the solution you'd like**
Update import progress for the user using websockets

**Describe alternatives you've considered**

**Additional context**
See: [/Src/WitsmlExplorer.Api/Workers/ImportLogDataWorker.cs#L76](https://github.com/equinor/witsml-explorer/blob/b4d6dd08b79c293a36ee2f69a5c8a5312feec85b/Src/WitsmlExplorer.Api/Workers/ImportLogDataWorker.cs#L76)
See: Issue #500

**Comment by eliasbruvik** [comment]
Implemented by #2292
