### ISSUE TITLE
Console app

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#549]
### User story: Console app  ###

This user story was born by the need for querying WITSML data from a Macbook. The access to WITSML clients for Mac is none, and although WitsmlExplorer is very helpful in many cases a simple CLI is much faster to get implemented. It is also seen as a trial test for verifying that the Witsml library alone can be used for querying WITSML data

### Acceptance criteria ###
- [X] Query active wellbores
- [X] Query logs for a given well/wellbore
- [X] Add list risks command to the console application
- [X] Extract settings to separate files
- [x] This is also a test for the usability for the Witsml library as a standalone solution for querying WITSML data.

Also, here are a few points that need to be addressed:
- [ ] [describe Constraint]
- [ ] [describe Constraint ]

### Resources ###

-  Lead resource: Equinor
-  Contributors:

**Comment by steinsiv** [comment]
Closing. Fulfilled since before PR #544
