### ISSUE TITLE
🐛Right clicking a log in content view should display a context menu with clickable items.

### ISSUE THREAD

**Issue by sudoole** [equinor/witsml-explorer#57]
**:bug: Describe the bug**
If i right click on a log in the content view when no rows are selected, I expect the context menu to allow me to click on e.g. `Properties`. In order for this to work now, I first have to left click it in order to check the log, and then right click it.

**To Reproduce**
1. Navigate to a wellbore with log objects, so that the content view displays the logs with checkable rows.
2. Right click a log.
3. No actions are enabled in the context menu.

**Expected behavior**
I expect that all actions which can be done on a single log should be enabled, similar to when first left clicking the row.

**Screenshots**
How it looks now:

![Screenshot 2020-12-18 at 11 34 46](https://user-images.githubusercontent.com/254171/102604968-106b6080-4125-11eb-91b8-512cafccc4cc.png)

How I suggest it should be:
![Screenshot 2020-12-18 at 11 35 47](https://user-images.githubusercontent.com/254171/102605187-36910080-4125-11eb-960b-370206fe850e.png)

**Comment by janburak** [comment]
1. Right-click single row when no other rows are marked -> mark the row
2. Right-click umarked row when other rows are marked -> mark the row and keep other rows marked
