### ISSUE TITLE
🐛Attempting to delete a Log without the correct access level gives incorrect feedback

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#637]
**:bug: Describe the bug**
If a user does not have permission to delete a Log, but they attempt to delete one, they get a toast saying the Log was successfully deleted even though it is still there.

**To Reproduce**
1. Access a server where you do not have permission to delete Logs
2. Drill down to Log level.
3. Try to delete a Log.
4. Observe toast saying Log was deleted and that the Log is still there. 

**Expected behavior**
An error message is displayed to the user telling them they do not have access to delete Logs.

**Screenshots**

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Browser: Chrome
 - Version: 92.0.4515.159

**Comment by steinsiv** [comment]
A related issue in this respect (**delete log**).

If the connection is broken between the API and WITSML server, the log will still be removed from GUI and appear to have been deleted. No other feedback is then given to user. 

In the image below `Caliper` seem to have been deleted when it has not.
![image](https://user-images.githubusercontent.com/1442452/133051790-d0fb1c8b-d63a-40b2-9634-27a7c67193c7.png)

**Comment by janburak** [comment]
The following message is shown when trying to delete a log with permission
![image](https://user-images.githubusercontent.com/66632214/236470530-63f5f983-8fbd-4b66-9dfb-11c0c4de67ce.png)
