### ISSUE TITLE
Add support for fetching wbGeometry objects💡

### ISSUE THREAD

**Issue by lindsve** [equinor/witsml-explorer#651]
**💡 Is your feature request related to a problem? Please describe.**
We need to be able to retrieve wbGeometry objects for a given wellbore

**Describe the solution you'd like**
The `Witsml` library should be extended with type mappings for fetching `wbGeometry` objects from a Witsml server

**Describe alternatives you've considered**
N/A

**Additional context**
This will be implemented within our team, this issue is mostly for informational purposes

**Comment by janburak** [comment]
Fixed by #1320 and #1638
