### ISSUE TITLE
🐛Many logs are not being copied and showing error 

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#653]
**:bug: Describe the bug**
Many logs are not being copied and showing error "Failed to copy curves for existing mnemonics to log. Copied a total of 0 rows". Encounter this error in many wellbores.

On further analysis of such logs, observed below points:

- For many logs, If we create a new log it will be able to copy data.

 Reference wellbore-NO 34/10-A-41 B (B-4247994) Log uid- L-4255912-Time
Mnemonic – GS_MWTI

- In some cases, few mnemonics, curve values are not being copied and creating null mnemonics. Also, if we try to copy such mnemonics into a new log they are showing same copy error. Reference wellbore-NO 34/10-E-2 AH (B-2179611) Mnemonic -DCHR Log uid-L-2179612

- Checked Log-"Workover - Time log" ( Uid: L-4255912-Time) in wellbore -NO 34/10-A-41 B (uid-B-4247994). There is only one Index curve "Time" for this log. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22211376/132514289-aaa9de82-4caf-45c9-a7d2-862d85f62f6b.png)

**Additional context**
Reported by Tata team

**Comment by steinsiv** [comment]
What would be the Expected result here?
 - Better feedback on success/failure
 - Atomic copy, all or nothing?
or similar, please elaborate on this for tasks to be concretized

**Comment by janburak** [comment]
Copying logs has been improved since. Copied "wellbore-NO 34/10-A-41 B (B-4247994) Log uid- L-4255912-Time" successfully.
