### ISSUE TITLE
🐛 Frontend use depth index as key, which turns out not to be unique.

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#655]
**:bug: Describe the bug**
React/ Frontend uses depth index as key, which turns out not to be unique in some cases.

**Screenshots**
The UI also can't handle the duplicated keys as seen in the following image:

![image](https://user-images.githubusercontent.com/22211376/132653268-fbb89d79-a83e-47d7-bf71-660ce20e8fe3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Originally reported as part of bug issue #439

**Comment by ThomasHalland** [comment]
Is this still a problem?

**Comment by eliasbruvik** [comment]
Closing this as indexes should be unique, and there are no other reported incidents of the bug in a while.
