### ISSUE TITLE
Fetch only objects that are returned by the GetCap

### ISSUE THREAD

**Issue by Pascal62223** [equinor/witsml-explorer#662]
**Is your feature request related to a problem? Please describe.**
Not all servers have complete implementation in term of GetFromStore / AddToStore etc ... for all the defined WITSML objects. When WE startup the default list of objects retrieved are well / wellbore / rig. When wellbore is expanded the rest of the objects are retrieved for display.

In scenario where a server doesn't support one of the object (e.g. rig) an exception is being thrown. The rig node is displayed (empty) but with a Back-end error.

**Describe the solution you'd like**
The solution aims at making the WE aware of the GetCap(), and first bypass the objects for which the GetFromStore is not supported. Log the information , and define how these 'non-supported' objects should be represented (e.g. not displayed, displayed but grayed out, displayed with "(not supported)" statement etc ...)

**Describe alternatives you've considered**

**Additional context**

**Comment by janburak** [comment]
Not prioritized for now, but would be a good enhancement

**Comment by eliasbruvik** [comment]
This has already been fixed. GetCap is used to determine which objects that will be disabled in the filter, and not shown at all. As the objects are now fetched when navigating to the object, and not when opening a wellbore, it won't be fetched either.
