### ISSUE TITLE
Well object - extend support to read "all" witsml well properties in frontend

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#687]
### User story: Well object - extend support to read "all" witsml well properties in frontend ###

As a user 
I want to be able  display  "all" witsml well properties (metadata)
so that I get all the details about the well.

### Acceptance criteria ###
- [ ] A table view of all witsml well properties in frontend
- [ ] Table containes all properties set as required in the [Well properties list](https://github.com/equinor/witsml-explorer/wiki/Well-property-list)

**Comment by Pascal62223** [comment]
I like the idea here and think it would be very  useful. The complexity is going to come from both aspect as far as I can see:

1. UX: I believe the well page (and any other object editor) must kept as simple as possible with the key information being accessed. Any additional property being accessed only on user request. For example through a "Show Advance" option.
2. Property definitions : Some well property such as CRS are going to be tricky to handle if editing is being allowed. Are all properties going to be editable ? If not, would the editing capability be a configuration that can be set at deployment time ?

**Comment by ThomasHalland** [comment]
The idea is good but we stick to the initial idea of the product to focus mainly on functionality which adds value and is based on real Use Cases. Hence we will extend the Well object support with new features as soon as it is demonstrated that somone needs them.

**Comment by eliasbruvik** [comment]
Closing this as per Thomas' comment. A new issue should be created when we have a use case.
