### ISSUE TITLE
🐛Copied logs are marked as active despite the original being inactive.

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#711]
**:bug: Describe the bug**
When copying logs the newly generated logs will be shown as active, even though the original object is not active.

The `objectGrowing` parameter is set to `true` on the server, ignoring the parameter passed by the copy request.

**To Reproduce**
1. Copy a which is not active
2. Notice the log is marked as active.

**Expected behavior**
The copied log has the same activity status as the original log.

**Additional context**
The `objectGrowing` parameter might not be set in the same way on every WITSML server.

**Comment by janburak** [comment]
Works as expected
