### ISSUE TITLE
🐛 Mismatch naming Time/time index between index curve and LogCurve Info 

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#721]
**:bug: Describe the bug**
Some providers have inconsistent naming of time index curve [Time vs time] and LogCurveInfo, this results an error in update to store situations from WitsmlExplorer.  

**Expected behavior**
Check if mnemonic has index curve and, if inconsistent naming, witsmlExplorer need to select the naming of time index used in LogCurveInfo in situations when updating store.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Look into the worker code for `CopyLogDataWorker`. There should be some code there that checks if the incoming mnemonics contain index column. If not, then it is added. This check is case sensitive so we might end up with duplicate index mnemonics

**Comment by janburak** [comment]
Fixed by #750
