### ISSUE TITLE
Create a correlation id for ongoing jobs / extend api with endpoint for  job status based on correlation id

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#723]
**Is your feature request related to a problem? Please describe.**
There is a need to get status for ongoing jobs. Is the job  still ongoing, has failed, is successful, etc.

**Describe the solution you'd like**

**Describe alternatives you've considered**
One possible solution is to extend with adding a correlation id assigned to each job in progress.
Extending the api with a new endpoint for returning job status based on correlation id will be very useful

**Additional context**

**Comment by steinsiv** [comment]
WE-393 with related story WE-557 fulfils this issue. Closing
