### ISSUE TITLE
🐛Error when using the datepicker

### ISSUE THREAD

**Issue by stigrus** [equinor/witsml-explorer#785]
**:bug: Describe the bug**
Error when using the datepicker to select start/end date/time when opening log data.

**Screenshots**
![Screenshot 2021-10-26 at 08 38 40](https://user-images.githubusercontent.com/49306816/138825160-6b5a7fec-596c-4fb2-a4bb-8c73013d482c.png)
![Screenshot 2021-10-26 at 08 38 51](https://user-images.githubusercontent.com/49306816/138825174-056641dc-f4c1-4059-995b-7ae8a77a7fef.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Comment by steinsiv** [comment]
I just confirmed this and got this error:
```
Unhandled Runtime Error
TypeError: utils.getDayText is not a function

Call Stack
eval
../../node_modules/@material-ui/pickers/esm/Calendar-11ae61f6.js (508:9)
```

It might be that Material UI datepicker has changed some internals?

As we are moving away from Material UI over to EDS, we should check if the component could be exchanged with an EDS equivalent when fixing this bug
