### ISSUE TITLE
💡Control user access to application

### ISSUE THREAD

**Issue by marmid74** [equinor/witsml-explorer#9]

**Comment by steinsiv** [comment]
Implemented through several earlier PRs. Closing
https://github.com/equinor/witsml-explorer/pull/1338
https://github.com/equinor/witsml-explorer/pull/1423
https://github.com/equinor/witsml-explorer/pull/1414
https://github.com/equinor/witsml-explorer/pull/1478
https://github.com/equinor/witsml-explorer/pull/1500
