### ISSUE TITLE
🐛 The GetCap request sent to WITSML server when testing server connection is invalid

### ISSUE THREAD

**Issue by kongxy10** [equinor/witsml-explorer#927]
**:bug: Describe the bug**
The GetCap request sent to WITSML server when testing server connection is invalid
The valid GetCap request should and should contain an OptionsIn parameter with only "dataVersion=1.4.1.1" field (for WITSML 1.4.1.1 server)
With current implementation, the OptionsIn equals to "returnElements=header-only", which is invalid for a GetCap request.
If the target server to test the connection validates the GetCap request, it will return an error for this request.

**To Reproduce**
Add or edit a server at the index
Click "test connection" and try to login Schlumberger DrillOps server 
An error response indicating the request was invalid returned.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/38779042/147479012-c88860bd-170b-42e2-8a84-7a35505f49c2.png">

[22:00:59 FTL] Something went wrong: System.Exception: Error while testing connection: -1 - DrillOps WITSML Server internal error.. returnElements: header-only is illegal
   at Witsml.WitsmlClient.TestConnectionAsync() in C:\Repos\witsml-explorer\Src\Witsml\WitsmlClient.cs:line 280
   at WitsmlExplorer.Api.Services.CredentialsService.VerifyCredentials(Uri serverUrl, Credentials credentials) in C:\Repos\witsml-explorer\Src\WitsmlExplorer.Api\Services\CredentialsService.cs:line 78

**Expected behavior**
An OK response should be returned

**Additional context**
Suggestion about how to fix: change the GetCap request to make it compliant with WITSML 1.4.1 Store API specification.

**Comment by kongxy10** [comment]
Some further discussion: if the purpose of sending GetCap request is to validate the credentials only, whether changing it to a GetVersion request can make it more efficient?

**Comment by lindsve** [comment]
> Some further discussion: if the purpose of sending GetCap request is to validate the credentials only, whether changing it to a GetVersion request can make it more efficient?

Yup, this request is just to verify credentials so I like the suggestion to use GetVersion instead 👍

**Comment by steinsiv** [comment]
Created an Issue for this https://github.com/equinor/witsml-explorer/issues/952

I think we should still merge [PR# 926](https://github.com/equinor/witsml-explorer/pull/926) first though, as not using dataversion will produce an error as is
