### ISSUE TITLE
Switch to official node:alpline base image for frontend

### ISSUE THREAD

**Issue by kongxy10** [equinor/witsml-explorer#928]
**Is your feature request related to a problem? Please describe.**
The current base image for frontend, mhart/alpine-node:16.1 is not so up-to-date.
Scanning this base image with Trivy, https://aquasecurity.github.io/trivy/v0.22.0/,
it is detected that version of the base alpine linux is 3.13.5. 
The scanning result indicates that there are some security vulnerabilities with this version of alpine (as well as nodejs), and these vulnerabilities got fixed in the higher version (The latest version of alpine available now on docker hub is 3.15.)
However, there's no newer version of this mhart/alpine-node now.

**Describe the solution you'd like**
We can switch to the official nodejs image. For example, node:16-alpine3.14 (as of now equivalent to 16.13.1-alpine3.14 )
**Pro**: we can save the effort to manually/explicitly upgrade minor/patch version of nodejs and its alpine base
Note: 
1. The specific referenced version of Node and Alpine of this image will keep getting evolved for the tags that only contain major or minor versions. For example, node:16-alpine3.14 may refer to node v16.12.0 in the past, and 16.14.0 in the future. And it is based on alpine:3.14,  (https://hub.docker.com/_/alpine) this tag of alpine may refer to alpine v 3.14.1 in the past, and 3.14.5 in the future. 
2. build the image with argument --pull to always look for newer representation
e.g.
docker build **--pull** -t docker.pkg.github.com/equinor/witsml-explorer/witsmlexplorer-frontend -f Dockerfile-frontend .
otherwise docker might still use the locally cached version of base image first.

**Con**: It may lead to indefinite build results each time when we build the image, since the referenced version of node and alpine will keep being updated.

**Comment by kongxy10** [comment]
scan with command:
trivy image mhart/alpine-node:16.1

<img width="902" alt="image" src="https://user-images.githubusercontent.com/38779042/147489563-4a1abdcb-0c6f-45fb-add3-67e698b9f876.png">

**Comment by steinsiv** [comment]
Closing Issue. Fixed through PR # 923
