### ISSUE TITLE
🐛 When copying logs. Screen blanks out with an exception in console

### ISSUE THREAD

**Issue by steinsiv** [equinor/witsml-explorer#985]
**:bug: Describe the bug**
Websocket jobmessage produces an exception when view is trying to refresh after showing snackbar.

**To Reproduce**
Observed when receiving events from other parties after jobs initiated by them

**Expected behavior**
No error after refreshing

example websocket message received by browser:
```json
{"type":1,"target":"jobFinished","arguments":[{"serverUrl":"https://example-server.arpa/store/witsml","isSuccess":true,"message":"371 rows copied","reason":null,"description":null}]}{"type":1,"target":"refresh","arguments":[{"entityType":"LogObject","wellUid":"W-5031588","wellboreUid":"B-5031588","logObjectUid":"b5ad3422-7dbc-42fc-a07a-0ca51f0181bf","refreshType":"Update","serverUrl":"https://example-server.arpa/store/witsml"}]}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1442452/151558835-28b9e205-8211-45f6-9539-9245672312df.png)

**Additional context**
javascript code triggering the error:
```js
            case Et.UpdateLogObject:
                return ha(e, t);
```
.
.

```js
            return e[t].wellbores[r].logs.findIndex((function(e) {
```

**Comment by janburak** [comment]
Possibly fixed by #1813
